// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Regenerate with:  node scripts/gen-emoji.mjs
//
// Source: scripts/emoji-source.json (unicode-emoji-json data-by-group.json),
// vendored so the build needs no network. 1906 emoji across the 9
// standard Unicode groups, with search keywords derived from each emoji's name
// and slug.
//
// This file is committed on purpose: the release build must not have to run the
// generator. emojiData.test.ts re-runs it and compares against this file, so a
// stale commit fails CI rather than shipping an out-of-date set.
import type { EmojiGroup } from "./emojiData";

export const generatedEmojiGroups: EmojiGroup[] = [
  {
    name: "Smileys & Emotion",
    emojis: [
    { emoji: "😀", keywords: "grinning face" },
    { emoji: "😃", keywords: "grinning face with big eyes" },
    { emoji: "😄", keywords: "grinning face with smiling eyes" },
    { emoji: "😁", keywords: "beaming face with smiling eyes" },
    { emoji: "😆", keywords: "grinning squinting face" },
    { emoji: "😅", keywords: "grinning face with sweat" },
    { emoji: "🤣", keywords: "rolling on the floor laughing" },
    { emoji: "😂", keywords: "face with tears of joy" },
    { emoji: "🙂", keywords: "slightly smiling face" },
    { emoji: "🙃", keywords: "upside down face" },
    { emoji: "🫠", keywords: "melting face" },
    { emoji: "😉", keywords: "winking face" },
    { emoji: "😊", keywords: "smiling face with eyes" },
    { emoji: "😇", keywords: "smiling face with halo" },
    { emoji: "🥰", keywords: "smiling face with hearts" },
    { emoji: "😍", keywords: "smiling face with heart eyes" },
    { emoji: "🤩", keywords: "star struck" },
    { emoji: "😘", keywords: "face blowing a kiss" },
    { emoji: "😗", keywords: "kissing face" },
    { emoji: "☺️", keywords: "smiling face" },
    { emoji: "😚", keywords: "kissing face with closed eyes" },
    { emoji: "😙", keywords: "kissing face with smiling eyes" },
    { emoji: "🥲", keywords: "smiling face with tear" },
    { emoji: "😋", keywords: "face savoring food" },
    { emoji: "😛", keywords: "face with tongue" },
    { emoji: "😜", keywords: "winking face with tongue" },
    { emoji: "🤪", keywords: "zany face" },
    { emoji: "😝", keywords: "squinting face with tongue" },
    { emoji: "🤑", keywords: "money mouth face" },
    { emoji: "🤗", keywords: "smiling face with open hands" },
    { emoji: "🤭", keywords: "face with hand over mouth" },
    { emoji: "🫢", keywords: "face with open eyes and hand over mouth" },
    { emoji: "🫣", keywords: "face with peeking eye" },
    { emoji: "🤫", keywords: "shushing face" },
    { emoji: "🤔", keywords: "thinking face" },
    { emoji: "🫡", keywords: "saluting face" },
    { emoji: "🤐", keywords: "zipper mouth face" },
    { emoji: "🤨", keywords: "face with raised eyebrow" },
    { emoji: "😐", keywords: "neutral face" },
    { emoji: "😑", keywords: "expressionless face" },
    { emoji: "😶", keywords: "face without mouth" },
    { emoji: "🫥", keywords: "dotted line face" },
    { emoji: "😶‍🌫️", keywords: "face in clouds" },
    { emoji: "😏", keywords: "smirking face" },
    { emoji: "😒", keywords: "unamused face" },
    { emoji: "🙄", keywords: "face with rolling eyes" },
    { emoji: "😬", keywords: "grimacing face" },
    { emoji: "😮‍💨", keywords: "face exhaling" },
    { emoji: "🤥", keywords: "lying face" },
    { emoji: "🫨", keywords: "shaking face" },
    { emoji: "🙂‍↔️", keywords: "head shaking horizontally" },
    { emoji: "🙂‍↕️", keywords: "head shaking vertically" },
    { emoji: "😌", keywords: "relieved face" },
    { emoji: "😔", keywords: "pensive face" },
    { emoji: "😪", keywords: "sleepy face" },
    { emoji: "🤤", keywords: "drooling face" },
    { emoji: "😴", keywords: "sleeping face" },
    { emoji: "🫩", keywords: "face with bags under eyes" },
    { emoji: "😷", keywords: "face with medical mask" },
    { emoji: "🤒", keywords: "face with thermometer" },
    { emoji: "🤕", keywords: "face with head bandage" },
    { emoji: "🤢", keywords: "nauseated face" },
    { emoji: "🤮", keywords: "face vomiting" },
    { emoji: "🤧", keywords: "sneezing face" },
    { emoji: "🥵", keywords: "hot face" },
    { emoji: "🥶", keywords: "cold face" },
    { emoji: "🥴", keywords: "woozy face" },
    { emoji: "😵", keywords: "face with crossed out eyes" },
    { emoji: "😵‍💫", keywords: "face with spiral eyes" },
    { emoji: "🤯", keywords: "exploding head" },
    { emoji: "🤠", keywords: "cowboy hat face" },
    { emoji: "🥳", keywords: "partying face" },
    { emoji: "🥸", keywords: "disguised face" },
    { emoji: "😎", keywords: "smiling face with sunglasses" },
    { emoji: "🤓", keywords: "nerd face" },
    { emoji: "🧐", keywords: "face with monocle" },
    { emoji: "😕", keywords: "confused face" },
    { emoji: "🫤", keywords: "face with diagonal mouth" },
    { emoji: "😟", keywords: "worried face" },
    { emoji: "🙁", keywords: "slightly frowning face" },
    { emoji: "☹️", keywords: "frowning face" },
    { emoji: "😮", keywords: "face with open mouth" },
    { emoji: "😯", keywords: "hushed face" },
    { emoji: "😲", keywords: "astonished face" },
    { emoji: "😳", keywords: "flushed face" },
    { emoji: "🥺", keywords: "pleading face" },
    { emoji: "🥹", keywords: "face holding back tears" },
    { emoji: "😦", keywords: "frowning face with open mouth" },
    { emoji: "😧", keywords: "anguished face" },
    { emoji: "😨", keywords: "fearful face" },
    { emoji: "😰", keywords: "anxious face with sweat" },
    { emoji: "😥", keywords: "sad but relieved face" },
    { emoji: "😢", keywords: "crying face" },
    { emoji: "😭", keywords: "loudly crying face" },
    { emoji: "😱", keywords: "face screaming in fear" },
    { emoji: "😖", keywords: "confounded face" },
    { emoji: "😣", keywords: "persevering face" },
    { emoji: "😞", keywords: "disappointed face" },
    { emoji: "😓", keywords: "downcast face with sweat" },
    { emoji: "😩", keywords: "weary face" },
    { emoji: "😫", keywords: "tired face" },
    { emoji: "🥱", keywords: "yawning face" },
    { emoji: "😤", keywords: "face with steam from nose" },
    { emoji: "😡", keywords: "enraged face" },
    { emoji: "😠", keywords: "angry face" },
    { emoji: "🤬", keywords: "face with symbols on mouth" },
    { emoji: "😈", keywords: "smiling face with horns" },
    { emoji: "👿", keywords: "angry face with horns" },
    { emoji: "💀", keywords: "skull" },
    { emoji: "☠️", keywords: "skull and crossbones" },
    { emoji: "💩", keywords: "pile of poo" },
    { emoji: "🤡", keywords: "clown face" },
    { emoji: "👹", keywords: "ogre" },
    { emoji: "👺", keywords: "goblin" },
    { emoji: "👻", keywords: "ghost" },
    { emoji: "👽", keywords: "alien" },
    { emoji: "👾", keywords: "alien monster" },
    { emoji: "🤖", keywords: "robot" },
    { emoji: "😺", keywords: "grinning cat" },
    { emoji: "😸", keywords: "grinning cat with smiling eyes" },
    { emoji: "😹", keywords: "cat with tears of joy" },
    { emoji: "😻", keywords: "smiling cat with heart eyes" },
    { emoji: "😼", keywords: "cat with wry smile" },
    { emoji: "😽", keywords: "kissing cat" },
    { emoji: "🙀", keywords: "weary cat" },
    { emoji: "😿", keywords: "crying cat" },
    { emoji: "😾", keywords: "pouting cat" },
    { emoji: "🙈", keywords: "see no evil monkey" },
    { emoji: "🙉", keywords: "hear no evil monkey" },
    { emoji: "🙊", keywords: "speak no evil monkey" },
    { emoji: "💌", keywords: "love letter" },
    { emoji: "💘", keywords: "heart with arrow" },
    { emoji: "💝", keywords: "heart with ribbon" },
    { emoji: "💖", keywords: "sparkling heart" },
    { emoji: "💗", keywords: "growing heart" },
    { emoji: "💓", keywords: "beating heart" },
    { emoji: "💞", keywords: "revolving hearts" },
    { emoji: "💕", keywords: "two hearts" },
    { emoji: "💟", keywords: "heart decoration" },
    { emoji: "❣️", keywords: "heart exclamation" },
    { emoji: "💔", keywords: "broken heart" },
    { emoji: "❤️‍🔥", keywords: "heart on fire" },
    { emoji: "❤️‍🩹", keywords: "mending heart" },
    { emoji: "❤️", keywords: "red heart" },
    { emoji: "🩷", keywords: "pink heart" },
    { emoji: "🧡", keywords: "orange heart" },
    { emoji: "💛", keywords: "yellow heart" },
    { emoji: "💚", keywords: "green heart" },
    { emoji: "💙", keywords: "blue heart" },
    { emoji: "🩵", keywords: "light blue heart" },
    { emoji: "💜", keywords: "purple heart" },
    { emoji: "🤎", keywords: "brown heart" },
    { emoji: "🖤", keywords: "black heart" },
    { emoji: "🩶", keywords: "grey heart" },
    { emoji: "🤍", keywords: "white heart" },
    { emoji: "💋", keywords: "kiss mark" },
    { emoji: "💯", keywords: "hundred points" },
    { emoji: "💢", keywords: "anger symbol" },
    { emoji: "💥", keywords: "collision" },
    { emoji: "💫", keywords: "dizzy" },
    { emoji: "💦", keywords: "sweat droplets" },
    { emoji: "💨", keywords: "dashing away" },
    { emoji: "🕳️", keywords: "hole" },
    { emoji: "💬", keywords: "speech balloon" },
    { emoji: "👁️‍🗨️", keywords: "eye in speech bubble" },
    { emoji: "🗨️", keywords: "left speech bubble" },
    { emoji: "🗯️", keywords: "right anger bubble" },
    { emoji: "💭", keywords: "thought balloon" },
    { emoji: "💤", keywords: "zzz" },
    ],
  },
  {
    name: "People & Body",
    emojis: [
    { emoji: "👋", keywords: "waving hand" },
    { emoji: "🤚", keywords: "raised back of hand" },
    { emoji: "🖐️", keywords: "hand with fingers splayed" },
    { emoji: "✋", keywords: "raised hand" },
    { emoji: "🖖", keywords: "vulcan salute" },
    { emoji: "🫱", keywords: "rightwards hand" },
    { emoji: "🫲", keywords: "leftwards hand" },
    { emoji: "🫳", keywords: "palm down hand" },
    { emoji: "🫴", keywords: "palm up hand" },
    { emoji: "🫷", keywords: "leftwards pushing hand" },
    { emoji: "🫸", keywords: "rightwards pushing hand" },
    { emoji: "👌", keywords: "ok hand" },
    { emoji: "🤌", keywords: "pinched fingers" },
    { emoji: "🤏", keywords: "pinching hand" },
    { emoji: "✌️", keywords: "victory hand" },
    { emoji: "🤞", keywords: "crossed fingers" },
    { emoji: "🫰", keywords: "hand with index finger and thumb crossed" },
    { emoji: "🤟", keywords: "love you gesture" },
    { emoji: "🤘", keywords: "sign of the horns" },
    { emoji: "🤙", keywords: "call me hand" },
    { emoji: "👈", keywords: "backhand index pointing left" },
    { emoji: "👉", keywords: "backhand index pointing right" },
    { emoji: "👆", keywords: "backhand index pointing up" },
    { emoji: "🖕", keywords: "middle finger" },
    { emoji: "👇", keywords: "backhand index pointing down" },
    { emoji: "☝️", keywords: "index pointing up" },
    { emoji: "🫵", keywords: "index pointing at the viewer" },
    { emoji: "👍", keywords: "thumbs up" },
    { emoji: "👎", keywords: "thumbs down" },
    { emoji: "✊", keywords: "raised fist" },
    { emoji: "👊", keywords: "oncoming fist" },
    { emoji: "🤛", keywords: "left facing fist" },
    { emoji: "🤜", keywords: "right facing fist" },
    { emoji: "👏", keywords: "clapping hands" },
    { emoji: "🙌", keywords: "raising hands" },
    { emoji: "🫶", keywords: "heart hands" },
    { emoji: "👐", keywords: "open hands" },
    { emoji: "🤲", keywords: "palms up together" },
    { emoji: "🤝", keywords: "handshake" },
    { emoji: "🙏", keywords: "folded hands" },
    { emoji: "✍️", keywords: "writing hand" },
    { emoji: "💅", keywords: "nail polish" },
    { emoji: "🤳", keywords: "selfie" },
    { emoji: "💪", keywords: "flexed biceps" },
    { emoji: "🦾", keywords: "mechanical arm" },
    { emoji: "🦿", keywords: "mechanical leg" },
    { emoji: "🦵", keywords: "leg" },
    { emoji: "🦶", keywords: "foot" },
    { emoji: "👂", keywords: "ear" },
    { emoji: "🦻", keywords: "ear with hearing aid" },
    { emoji: "👃", keywords: "nose" },
    { emoji: "🧠", keywords: "brain" },
    { emoji: "🫀", keywords: "anatomical heart" },
    { emoji: "🫁", keywords: "lungs" },
    { emoji: "🦷", keywords: "tooth" },
    { emoji: "🦴", keywords: "bone" },
    { emoji: "👀", keywords: "eyes" },
    { emoji: "👁️", keywords: "eye" },
    { emoji: "👅", keywords: "tongue" },
    { emoji: "👄", keywords: "mouth" },
    { emoji: "🫦", keywords: "biting lip" },
    { emoji: "👶", keywords: "baby" },
    { emoji: "🧒", keywords: "child" },
    { emoji: "👦", keywords: "boy" },
    { emoji: "👧", keywords: "girl" },
    { emoji: "🧑", keywords: "person" },
    { emoji: "👱", keywords: "person blond hair" },
    { emoji: "👨", keywords: "man" },
    { emoji: "🧔", keywords: "person beard" },
    { emoji: "🧔‍♂️", keywords: "man beard" },
    { emoji: "🧔‍♀️", keywords: "woman beard" },
    { emoji: "👨‍🦰", keywords: "man red hair" },
    { emoji: "👨‍🦱", keywords: "man curly hair" },
    { emoji: "👨‍🦳", keywords: "man white hair" },
    { emoji: "👨‍🦲", keywords: "man bald" },
    { emoji: "👩", keywords: "woman" },
    { emoji: "👩‍🦰", keywords: "woman red hair" },
    { emoji: "🧑‍🦰", keywords: "person red hair" },
    { emoji: "👩‍🦱", keywords: "woman curly hair" },
    { emoji: "🧑‍🦱", keywords: "person curly hair" },
    { emoji: "👩‍🦳", keywords: "woman white hair" },
    { emoji: "🧑‍🦳", keywords: "person white hair" },
    { emoji: "👩‍🦲", keywords: "woman bald" },
    { emoji: "🧑‍🦲", keywords: "person bald" },
    { emoji: "👱‍♀️", keywords: "woman blond hair" },
    { emoji: "👱‍♂️", keywords: "man blond hair" },
    { emoji: "🧓", keywords: "older person" },
    { emoji: "👴", keywords: "old man" },
    { emoji: "👵", keywords: "old woman" },
    { emoji: "🙍", keywords: "person frowning" },
    { emoji: "🙍‍♂️", keywords: "man frowning" },
    { emoji: "🙍‍♀️", keywords: "woman frowning" },
    { emoji: "🙎", keywords: "person pouting" },
    { emoji: "🙎‍♂️", keywords: "man pouting" },
    { emoji: "🙎‍♀️", keywords: "woman pouting" },
    { emoji: "🙅", keywords: "person gesturing no" },
    { emoji: "🙅‍♂️", keywords: "man gesturing no" },
    { emoji: "🙅‍♀️", keywords: "woman gesturing no" },
    { emoji: "🙆", keywords: "person gesturing ok" },
    { emoji: "🙆‍♂️", keywords: "man gesturing ok" },
    { emoji: "🙆‍♀️", keywords: "woman gesturing ok" },
    { emoji: "💁", keywords: "person tipping hand" },
    { emoji: "💁‍♂️", keywords: "man tipping hand" },
    { emoji: "💁‍♀️", keywords: "woman tipping hand" },
    { emoji: "🙋", keywords: "person raising hand" },
    { emoji: "🙋‍♂️", keywords: "man raising hand" },
    { emoji: "🙋‍♀️", keywords: "woman raising hand" },
    { emoji: "🧏", keywords: "deaf person" },
    { emoji: "🧏‍♂️", keywords: "deaf man" },
    { emoji: "🧏‍♀️", keywords: "deaf woman" },
    { emoji: "🙇", keywords: "person bowing" },
    { emoji: "🙇‍♂️", keywords: "man bowing" },
    { emoji: "🙇‍♀️", keywords: "woman bowing" },
    { emoji: "🤦", keywords: "person facepalming" },
    { emoji: "🤦‍♂️", keywords: "man facepalming" },
    { emoji: "🤦‍♀️", keywords: "woman facepalming" },
    { emoji: "🤷", keywords: "person shrugging" },
    { emoji: "🤷‍♂️", keywords: "man shrugging" },
    { emoji: "🤷‍♀️", keywords: "woman shrugging" },
    { emoji: "🧑‍⚕️", keywords: "health worker" },
    { emoji: "👨‍⚕️", keywords: "man health worker" },
    { emoji: "👩‍⚕️", keywords: "woman health worker" },
    { emoji: "🧑‍🎓", keywords: "student" },
    { emoji: "👨‍🎓", keywords: "man student" },
    { emoji: "👩‍🎓", keywords: "woman student" },
    { emoji: "🧑‍🏫", keywords: "teacher" },
    { emoji: "👨‍🏫", keywords: "man teacher" },
    { emoji: "👩‍🏫", keywords: "woman teacher" },
    { emoji: "🧑‍⚖️", keywords: "judge" },
    { emoji: "👨‍⚖️", keywords: "man judge" },
    { emoji: "👩‍⚖️", keywords: "woman judge" },
    { emoji: "🧑‍🌾", keywords: "farmer" },
    { emoji: "👨‍🌾", keywords: "man farmer" },
    { emoji: "👩‍🌾", keywords: "woman farmer" },
    { emoji: "🧑‍🍳", keywords: "cook" },
    { emoji: "👨‍🍳", keywords: "man cook" },
    { emoji: "👩‍🍳", keywords: "woman cook" },
    { emoji: "🧑‍🔧", keywords: "mechanic" },
    { emoji: "👨‍🔧", keywords: "man mechanic" },
    { emoji: "👩‍🔧", keywords: "woman mechanic" },
    { emoji: "🧑‍🏭", keywords: "factory worker" },
    { emoji: "👨‍🏭", keywords: "man factory worker" },
    { emoji: "👩‍🏭", keywords: "woman factory worker" },
    { emoji: "🧑‍💼", keywords: "office worker" },
    { emoji: "👨‍💼", keywords: "man office worker" },
    { emoji: "👩‍💼", keywords: "woman office worker" },
    { emoji: "🧑‍🔬", keywords: "scientist" },
    { emoji: "👨‍🔬", keywords: "man scientist" },
    { emoji: "👩‍🔬", keywords: "woman scientist" },
    { emoji: "🧑‍💻", keywords: "technologist" },
    { emoji: "👨‍💻", keywords: "man technologist" },
    { emoji: "👩‍💻", keywords: "woman technologist" },
    { emoji: "🧑‍🎤", keywords: "singer" },
    { emoji: "👨‍🎤", keywords: "man singer" },
    { emoji: "👩‍🎤", keywords: "woman singer" },
    { emoji: "🧑‍🎨", keywords: "artist" },
    { emoji: "👨‍🎨", keywords: "man artist" },
    { emoji: "👩‍🎨", keywords: "woman artist" },
    { emoji: "🧑‍✈️", keywords: "pilot" },
    { emoji: "👨‍✈️", keywords: "man pilot" },
    { emoji: "👩‍✈️", keywords: "woman pilot" },
    { emoji: "🧑‍🚀", keywords: "astronaut" },
    { emoji: "👨‍🚀", keywords: "man astronaut" },
    { emoji: "👩‍🚀", keywords: "woman astronaut" },
    { emoji: "🧑‍🚒", keywords: "firefighter" },
    { emoji: "👨‍🚒", keywords: "man firefighter" },
    { emoji: "👩‍🚒", keywords: "woman firefighter" },
    { emoji: "👮", keywords: "police officer" },
    { emoji: "👮‍♂️", keywords: "man police officer" },
    { emoji: "👮‍♀️", keywords: "woman police officer" },
    { emoji: "🕵️", keywords: "detective" },
    { emoji: "🕵️‍♂️", keywords: "man detective" },
    { emoji: "🕵️‍♀️", keywords: "woman detective" },
    { emoji: "💂", keywords: "guard" },
    { emoji: "💂‍♂️", keywords: "man guard" },
    { emoji: "💂‍♀️", keywords: "woman guard" },
    { emoji: "🥷", keywords: "ninja" },
    { emoji: "👷", keywords: "construction worker" },
    { emoji: "👷‍♂️", keywords: "man construction worker" },
    { emoji: "👷‍♀️", keywords: "woman construction worker" },
    { emoji: "🫅", keywords: "person with crown" },
    { emoji: "🤴", keywords: "prince" },
    { emoji: "👸", keywords: "princess" },
    { emoji: "👳", keywords: "person wearing turban" },
    { emoji: "👳‍♂️", keywords: "man wearing turban" },
    { emoji: "👳‍♀️", keywords: "woman wearing turban" },
    { emoji: "👲", keywords: "person with skullcap" },
    { emoji: "🧕", keywords: "woman with headscarf" },
    { emoji: "🤵", keywords: "person in tuxedo" },
    { emoji: "🤵‍♂️", keywords: "man in tuxedo" },
    { emoji: "🤵‍♀️", keywords: "woman in tuxedo" },
    { emoji: "👰", keywords: "person with veil" },
    { emoji: "👰‍♂️", keywords: "man with veil" },
    { emoji: "👰‍♀️", keywords: "woman with veil" },
    { emoji: "🤰", keywords: "pregnant woman" },
    { emoji: "🫃", keywords: "pregnant man" },
    { emoji: "🫄", keywords: "pregnant person" },
    { emoji: "🤱", keywords: "breast feeding" },
    { emoji: "👩‍🍼", keywords: "woman feeding baby" },
    { emoji: "👨‍🍼", keywords: "man feeding baby" },
    { emoji: "🧑‍🍼", keywords: "person feeding baby" },
    { emoji: "👼", keywords: "baby angel" },
    { emoji: "🎅", keywords: "santa claus" },
    { emoji: "🤶", keywords: "mrs claus" },
    { emoji: "🧑‍🎄", keywords: "mx claus" },
    { emoji: "🦸", keywords: "superhero" },
    { emoji: "🦸‍♂️", keywords: "man superhero" },
    { emoji: "🦸‍♀️", keywords: "woman superhero" },
    { emoji: "🦹", keywords: "supervillain" },
    { emoji: "🦹‍♂️", keywords: "man supervillain" },
    { emoji: "🦹‍♀️", keywords: "woman supervillain" },
    { emoji: "🧙", keywords: "mage" },
    { emoji: "🧙‍♂️", keywords: "man mage" },
    { emoji: "🧙‍♀️", keywords: "woman mage" },
    { emoji: "🧚", keywords: "fairy" },
    { emoji: "🧚‍♂️", keywords: "man fairy" },
    { emoji: "🧚‍♀️", keywords: "woman fairy" },
    { emoji: "🧛", keywords: "vampire" },
    { emoji: "🧛‍♂️", keywords: "man vampire" },
    { emoji: "🧛‍♀️", keywords: "woman vampire" },
    { emoji: "🧜", keywords: "merperson" },
    { emoji: "🧜‍♂️", keywords: "merman" },
    { emoji: "🧜‍♀️", keywords: "mermaid" },
    { emoji: "🧝", keywords: "elf" },
    { emoji: "🧝‍♂️", keywords: "man elf" },
    { emoji: "🧝‍♀️", keywords: "woman elf" },
    { emoji: "🧞", keywords: "genie" },
    { emoji: "🧞‍♂️", keywords: "man genie" },
    { emoji: "🧞‍♀️", keywords: "woman genie" },
    { emoji: "🧟", keywords: "zombie" },
    { emoji: "🧟‍♂️", keywords: "man zombie" },
    { emoji: "🧟‍♀️", keywords: "woman zombie" },
    { emoji: "🧌", keywords: "troll" },
    { emoji: "💆", keywords: "person getting massage" },
    { emoji: "💆‍♂️", keywords: "man getting massage" },
    { emoji: "💆‍♀️", keywords: "woman getting massage" },
    { emoji: "💇", keywords: "person getting haircut" },
    { emoji: "💇‍♂️", keywords: "man getting haircut" },
    { emoji: "💇‍♀️", keywords: "woman getting haircut" },
    { emoji: "🚶", keywords: "person walking" },
    { emoji: "🚶‍♂️", keywords: "man walking" },
    { emoji: "🚶‍♀️", keywords: "woman walking" },
    { emoji: "🚶‍➡️", keywords: "person walking facing right" },
    { emoji: "🚶‍♀️‍➡️", keywords: "woman walking facing right" },
    { emoji: "🚶‍♂️‍➡️", keywords: "man walking facing right" },
    { emoji: "🧍", keywords: "person standing" },
    { emoji: "🧍‍♂️", keywords: "man standing" },
    { emoji: "🧍‍♀️", keywords: "woman standing" },
    { emoji: "🧎", keywords: "person kneeling" },
    { emoji: "🧎‍♂️", keywords: "man kneeling" },
    { emoji: "🧎‍♀️", keywords: "woman kneeling" },
    { emoji: "🧎‍➡️", keywords: "person kneeling facing right" },
    { emoji: "🧎‍♀️‍➡️", keywords: "woman kneeling facing right" },
    { emoji: "🧎‍♂️‍➡️", keywords: "man kneeling facing right" },
    { emoji: "🧑‍🦯", keywords: "person with white cane" },
    { emoji: "🧑‍🦯‍➡️", keywords: "person with white cane facing right" },
    { emoji: "👨‍🦯", keywords: "man with white cane" },
    { emoji: "👨‍🦯‍➡️", keywords: "man with white cane facing right" },
    { emoji: "👩‍🦯", keywords: "woman with white cane" },
    { emoji: "👩‍🦯‍➡️", keywords: "woman with white cane facing right" },
    { emoji: "🧑‍🦼", keywords: "person in motorized wheelchair" },
    { emoji: "🧑‍🦼‍➡️", keywords: "person in motorized wheelchair facing right" },
    { emoji: "👨‍🦼", keywords: "man in motorized wheelchair" },
    { emoji: "👨‍🦼‍➡️", keywords: "man in motorized wheelchair facing right" },
    { emoji: "👩‍🦼", keywords: "woman in motorized wheelchair" },
    { emoji: "👩‍🦼‍➡️", keywords: "woman in motorized wheelchair facing right" },
    { emoji: "🧑‍🦽", keywords: "person in manual wheelchair" },
    { emoji: "🧑‍🦽‍➡️", keywords: "person in manual wheelchair facing right" },
    { emoji: "👨‍🦽", keywords: "man in manual wheelchair" },
    { emoji: "👨‍🦽‍➡️", keywords: "man in manual wheelchair facing right" },
    { emoji: "👩‍🦽", keywords: "woman in manual wheelchair" },
    { emoji: "👩‍🦽‍➡️", keywords: "woman in manual wheelchair facing right" },
    { emoji: "🏃", keywords: "person running" },
    { emoji: "🏃‍♂️", keywords: "man running" },
    { emoji: "🏃‍♀️", keywords: "woman running" },
    { emoji: "🏃‍➡️", keywords: "person running facing right" },
    { emoji: "🏃‍♀️‍➡️", keywords: "woman running facing right" },
    { emoji: "🏃‍♂️‍➡️", keywords: "man running facing right" },
    { emoji: "💃", keywords: "woman dancing" },
    { emoji: "🕺", keywords: "man dancing" },
    { emoji: "🕴️", keywords: "person in suit levitating" },
    { emoji: "👯", keywords: "people with bunny ears" },
    { emoji: "👯‍♂️", keywords: "men with bunny ears" },
    { emoji: "👯‍♀️", keywords: "women with bunny ears" },
    { emoji: "🧖", keywords: "person in steamy room" },
    { emoji: "🧖‍♂️", keywords: "man in steamy room" },
    { emoji: "🧖‍♀️", keywords: "woman in steamy room" },
    { emoji: "🧗", keywords: "person climbing" },
    { emoji: "🧗‍♂️", keywords: "man climbing" },
    { emoji: "🧗‍♀️", keywords: "woman climbing" },
    { emoji: "🤺", keywords: "person fencing" },
    { emoji: "🏇", keywords: "horse racing" },
    { emoji: "⛷️", keywords: "skier" },
    { emoji: "🏂", keywords: "snowboarder" },
    { emoji: "🏌️", keywords: "person golfing" },
    { emoji: "🏌️‍♂️", keywords: "man golfing" },
    { emoji: "🏌️‍♀️", keywords: "woman golfing" },
    { emoji: "🏄", keywords: "person surfing" },
    { emoji: "🏄‍♂️", keywords: "man surfing" },
    { emoji: "🏄‍♀️", keywords: "woman surfing" },
    { emoji: "🚣", keywords: "person rowing boat" },
    { emoji: "🚣‍♂️", keywords: "man rowing boat" },
    { emoji: "🚣‍♀️", keywords: "woman rowing boat" },
    { emoji: "🏊", keywords: "person swimming" },
    { emoji: "🏊‍♂️", keywords: "man swimming" },
    { emoji: "🏊‍♀️", keywords: "woman swimming" },
    { emoji: "⛹️", keywords: "person bouncing ball" },
    { emoji: "⛹️‍♂️", keywords: "man bouncing ball" },
    { emoji: "⛹️‍♀️", keywords: "woman bouncing ball" },
    { emoji: "🏋️", keywords: "person lifting weights" },
    { emoji: "🏋️‍♂️", keywords: "man lifting weights" },
    { emoji: "🏋️‍♀️", keywords: "woman lifting weights" },
    { emoji: "🚴", keywords: "person biking" },
    { emoji: "🚴‍♂️", keywords: "man biking" },
    { emoji: "🚴‍♀️", keywords: "woman biking" },
    { emoji: "🚵", keywords: "person mountain biking" },
    { emoji: "🚵‍♂️", keywords: "man mountain biking" },
    { emoji: "🚵‍♀️", keywords: "woman mountain biking" },
    { emoji: "🤸", keywords: "person cartwheeling" },
    { emoji: "🤸‍♂️", keywords: "man cartwheeling" },
    { emoji: "🤸‍♀️", keywords: "woman cartwheeling" },
    { emoji: "🤼", keywords: "people wrestling" },
    { emoji: "🤼‍♂️", keywords: "men wrestling" },
    { emoji: "🤼‍♀️", keywords: "women wrestling" },
    { emoji: "🤽", keywords: "person playing water polo" },
    { emoji: "🤽‍♂️", keywords: "man playing water polo" },
    { emoji: "🤽‍♀️", keywords: "woman playing water polo" },
    { emoji: "🤾", keywords: "person playing handball" },
    { emoji: "🤾‍♂️", keywords: "man playing handball" },
    { emoji: "🤾‍♀️", keywords: "woman playing handball" },
    { emoji: "🤹", keywords: "person juggling" },
    { emoji: "🤹‍♂️", keywords: "man juggling" },
    { emoji: "🤹‍♀️", keywords: "woman juggling" },
    { emoji: "🧘", keywords: "person in lotus position" },
    { emoji: "🧘‍♂️", keywords: "man in lotus position" },
    { emoji: "🧘‍♀️", keywords: "woman in lotus position" },
    { emoji: "🛀", keywords: "person taking bath" },
    { emoji: "🛌", keywords: "person in bed" },
    { emoji: "🧑‍🤝‍🧑", keywords: "people holding hands" },
    { emoji: "👭", keywords: "women holding hands" },
    { emoji: "👫", keywords: "woman and man holding hands" },
    { emoji: "👬", keywords: "men holding hands" },
    { emoji: "💏", keywords: "kiss" },
    { emoji: "👩‍❤️‍💋‍👨", keywords: "kiss woman man" },
    { emoji: "👨‍❤️‍💋‍👨", keywords: "kiss man" },
    { emoji: "👩‍❤️‍💋‍👩", keywords: "kiss woman" },
    { emoji: "💑", keywords: "couple with heart" },
    { emoji: "👩‍❤️‍👨", keywords: "couple with heart woman man" },
    { emoji: "👨‍❤️‍👨", keywords: "couple with heart man" },
    { emoji: "👩‍❤️‍👩", keywords: "couple with heart woman" },
    { emoji: "👨‍👩‍👦", keywords: "family man woman boy" },
    { emoji: "👨‍👩‍👧", keywords: "family man woman girl" },
    { emoji: "👨‍👩‍👧‍👦", keywords: "family man woman girl boy" },
    { emoji: "👨‍👩‍👦‍👦", keywords: "family man woman boy" },
    { emoji: "👨‍👩‍👧‍👧", keywords: "family man woman girl" },
    { emoji: "👨‍👨‍👦", keywords: "family man boy" },
    { emoji: "👨‍👨‍👧", keywords: "family man girl" },
    { emoji: "👨‍👨‍👧‍👦", keywords: "family man girl boy" },
    { emoji: "👨‍👨‍👦‍👦", keywords: "family man boy" },
    { emoji: "👨‍👨‍👧‍👧", keywords: "family man girl" },
    { emoji: "👩‍👩‍👦", keywords: "family woman boy" },
    { emoji: "👩‍👩‍👧", keywords: "family woman girl" },
    { emoji: "👩‍👩‍👧‍👦", keywords: "family woman girl boy" },
    { emoji: "👩‍👩‍👦‍👦", keywords: "family woman boy" },
    { emoji: "👩‍👩‍👧‍👧", keywords: "family woman girl" },
    { emoji: "👨‍👦", keywords: "family man boy" },
    { emoji: "👨‍👦‍👦", keywords: "family man boy" },
    { emoji: "👨‍👧", keywords: "family man girl" },
    { emoji: "👨‍👧‍👦", keywords: "family man girl boy" },
    { emoji: "👨‍👧‍👧", keywords: "family man girl" },
    { emoji: "👩‍👦", keywords: "family woman boy" },
    { emoji: "👩‍👦‍👦", keywords: "family woman boy" },
    { emoji: "👩‍👧", keywords: "family woman girl" },
    { emoji: "👩‍👧‍👦", keywords: "family woman girl boy" },
    { emoji: "👩‍👧‍👧", keywords: "family woman girl" },
    { emoji: "🗣️", keywords: "speaking head" },
    { emoji: "👤", keywords: "bust in silhouette" },
    { emoji: "👥", keywords: "busts in silhouette" },
    { emoji: "🫂", keywords: "people hugging" },
    { emoji: "👪", keywords: "family" },
    { emoji: "🧑‍🧑‍🧒", keywords: "family adult child" },
    { emoji: "🧑‍🧑‍🧒‍🧒", keywords: "family adult child" },
    { emoji: "🧑‍🧒", keywords: "family adult child" },
    { emoji: "🧑‍🧒‍🧒", keywords: "family adult child" },
    { emoji: "👣", keywords: "footprints" },
    { emoji: "🫆", keywords: "fingerprint" },
    ],
  },
  {
    name: "Animals & Nature",
    emojis: [
    { emoji: "🐵", keywords: "monkey face" },
    { emoji: "🐒", keywords: "monkey" },
    { emoji: "🦍", keywords: "gorilla" },
    { emoji: "🦧", keywords: "orangutan" },
    { emoji: "🐶", keywords: "dog face" },
    { emoji: "🐕", keywords: "dog" },
    { emoji: "🦮", keywords: "guide dog" },
    { emoji: "🐕‍🦺", keywords: "service dog" },
    { emoji: "🐩", keywords: "poodle" },
    { emoji: "🐺", keywords: "wolf" },
    { emoji: "🦊", keywords: "fox" },
    { emoji: "🦝", keywords: "raccoon" },
    { emoji: "🐱", keywords: "cat face" },
    { emoji: "🐈", keywords: "cat" },
    { emoji: "🐈‍⬛", keywords: "black cat" },
    { emoji: "🦁", keywords: "lion" },
    { emoji: "🐯", keywords: "tiger face" },
    { emoji: "🐅", keywords: "tiger" },
    { emoji: "🐆", keywords: "leopard" },
    { emoji: "🐴", keywords: "horse face" },
    { emoji: "🫎", keywords: "moose" },
    { emoji: "🫏", keywords: "donkey" },
    { emoji: "🐎", keywords: "horse" },
    { emoji: "🦄", keywords: "unicorn" },
    { emoji: "🦓", keywords: "zebra" },
    { emoji: "🦌", keywords: "deer" },
    { emoji: "🦬", keywords: "bison" },
    { emoji: "🐮", keywords: "cow face" },
    { emoji: "🐂", keywords: "ox" },
    { emoji: "🐃", keywords: "water buffalo" },
    { emoji: "🐄", keywords: "cow" },
    { emoji: "🐷", keywords: "pig face" },
    { emoji: "🐖", keywords: "pig" },
    { emoji: "🐗", keywords: "boar" },
    { emoji: "🐽", keywords: "pig nose" },
    { emoji: "🐏", keywords: "ram" },
    { emoji: "🐑", keywords: "ewe" },
    { emoji: "🐐", keywords: "goat" },
    { emoji: "🐪", keywords: "camel" },
    { emoji: "🐫", keywords: "two hump camel" },
    { emoji: "🦙", keywords: "llama" },
    { emoji: "🦒", keywords: "giraffe" },
    { emoji: "🐘", keywords: "elephant" },
    { emoji: "🦣", keywords: "mammoth" },
    { emoji: "🦏", keywords: "rhinoceros" },
    { emoji: "🦛", keywords: "hippopotamus" },
    { emoji: "🐭", keywords: "mouse face" },
    { emoji: "🐁", keywords: "mouse" },
    { emoji: "🐀", keywords: "rat" },
    { emoji: "🐹", keywords: "hamster" },
    { emoji: "🐰", keywords: "rabbit face" },
    { emoji: "🐇", keywords: "rabbit" },
    { emoji: "🐿️", keywords: "chipmunk" },
    { emoji: "🦫", keywords: "beaver" },
    { emoji: "🦔", keywords: "hedgehog" },
    { emoji: "🦇", keywords: "bat" },
    { emoji: "🐻", keywords: "bear" },
    { emoji: "🐻‍❄️", keywords: "polar bear" },
    { emoji: "🐨", keywords: "koala" },
    { emoji: "🐼", keywords: "panda" },
    { emoji: "🦥", keywords: "sloth" },
    { emoji: "🦦", keywords: "otter" },
    { emoji: "🦨", keywords: "skunk" },
    { emoji: "🦘", keywords: "kangaroo" },
    { emoji: "🦡", keywords: "badger" },
    { emoji: "🐾", keywords: "paw prints" },
    { emoji: "🦃", keywords: "turkey" },
    { emoji: "🐔", keywords: "chicken" },
    { emoji: "🐓", keywords: "rooster" },
    { emoji: "🐣", keywords: "hatching chick" },
    { emoji: "🐤", keywords: "baby chick" },
    { emoji: "🐥", keywords: "front facing baby chick" },
    { emoji: "🐦", keywords: "bird" },
    { emoji: "🐧", keywords: "penguin" },
    { emoji: "🕊️", keywords: "dove" },
    { emoji: "🦅", keywords: "eagle" },
    { emoji: "🦆", keywords: "duck" },
    { emoji: "🦢", keywords: "swan" },
    { emoji: "🦉", keywords: "owl" },
    { emoji: "🦤", keywords: "dodo" },
    { emoji: "🪶", keywords: "feather" },
    { emoji: "🦩", keywords: "flamingo" },
    { emoji: "🦚", keywords: "peacock" },
    { emoji: "🦜", keywords: "parrot" },
    { emoji: "🪽", keywords: "wing" },
    { emoji: "🐦‍⬛", keywords: "black bird" },
    { emoji: "🪿", keywords: "goose" },
    { emoji: "🐦‍🔥", keywords: "phoenix" },
    { emoji: "🐸", keywords: "frog" },
    { emoji: "🐊", keywords: "crocodile" },
    { emoji: "🐢", keywords: "turtle" },
    { emoji: "🦎", keywords: "lizard" },
    { emoji: "🐍", keywords: "snake" },
    { emoji: "🐲", keywords: "dragon face" },
    { emoji: "🐉", keywords: "dragon" },
    { emoji: "🦕", keywords: "sauropod" },
    { emoji: "🦖", keywords: "t rex" },
    { emoji: "🐳", keywords: "spouting whale" },
    { emoji: "🐋", keywords: "whale" },
    { emoji: "🐬", keywords: "dolphin" },
    { emoji: "🦭", keywords: "seal" },
    { emoji: "🐟", keywords: "fish" },
    { emoji: "🐠", keywords: "tropical fish" },
    { emoji: "🐡", keywords: "blowfish" },
    { emoji: "🦈", keywords: "shark" },
    { emoji: "🐙", keywords: "octopus" },
    { emoji: "🐚", keywords: "spiral shell" },
    { emoji: "🪸", keywords: "coral" },
    { emoji: "🪼", keywords: "jellyfish" },
    { emoji: "🦀", keywords: "crab" },
    { emoji: "🦞", keywords: "lobster" },
    { emoji: "🦐", keywords: "shrimp" },
    { emoji: "🦑", keywords: "squid" },
    { emoji: "🦪", keywords: "oyster" },
    { emoji: "🐌", keywords: "snail" },
    { emoji: "🦋", keywords: "butterfly" },
    { emoji: "🐛", keywords: "bug" },
    { emoji: "🐜", keywords: "ant" },
    { emoji: "🐝", keywords: "honeybee" },
    { emoji: "🪲", keywords: "beetle" },
    { emoji: "🐞", keywords: "lady beetle" },
    { emoji: "🦗", keywords: "cricket" },
    { emoji: "🪳", keywords: "cockroach" },
    { emoji: "🕷️", keywords: "spider" },
    { emoji: "🕸️", keywords: "spider web" },
    { emoji: "🦂", keywords: "scorpion" },
    { emoji: "🦟", keywords: "mosquito" },
    { emoji: "🪰", keywords: "fly" },
    { emoji: "🪱", keywords: "worm" },
    { emoji: "🦠", keywords: "microbe" },
    { emoji: "💐", keywords: "bouquet" },
    { emoji: "🌸", keywords: "cherry blossom" },
    { emoji: "💮", keywords: "white flower" },
    { emoji: "🪷", keywords: "lotus" },
    { emoji: "🏵️", keywords: "rosette" },
    { emoji: "🌹", keywords: "rose" },
    { emoji: "🥀", keywords: "wilted flower" },
    { emoji: "🌺", keywords: "hibiscus" },
    { emoji: "🌻", keywords: "sunflower" },
    { emoji: "🌼", keywords: "blossom" },
    { emoji: "🌷", keywords: "tulip" },
    { emoji: "🪻", keywords: "hyacinth" },
    { emoji: "🌱", keywords: "seedling" },
    { emoji: "🪴", keywords: "potted plant" },
    { emoji: "🌲", keywords: "evergreen tree" },
    { emoji: "🌳", keywords: "deciduous tree" },
    { emoji: "🌴", keywords: "palm tree" },
    { emoji: "🌵", keywords: "cactus" },
    { emoji: "🌾", keywords: "sheaf of rice" },
    { emoji: "🌿", keywords: "herb" },
    { emoji: "☘️", keywords: "shamrock" },
    { emoji: "🍀", keywords: "four leaf clover" },
    { emoji: "🍁", keywords: "maple leaf" },
    { emoji: "🍂", keywords: "fallen leaf" },
    { emoji: "🍃", keywords: "leaf fluttering in wind" },
    { emoji: "🪹", keywords: "empty nest" },
    { emoji: "🪺", keywords: "nest with eggs" },
    { emoji: "🍄", keywords: "mushroom" },
    { emoji: "🪾", keywords: "leafless tree" },
    ],
  },
  {
    name: "Food & Drink",
    emojis: [
    { emoji: "🍇", keywords: "grapes" },
    { emoji: "🍈", keywords: "melon" },
    { emoji: "🍉", keywords: "watermelon" },
    { emoji: "🍊", keywords: "tangerine" },
    { emoji: "🍋", keywords: "lemon" },
    { emoji: "🍋‍🟩", keywords: "lime" },
    { emoji: "🍌", keywords: "banana" },
    { emoji: "🍍", keywords: "pineapple" },
    { emoji: "🥭", keywords: "mango" },
    { emoji: "🍎", keywords: "red apple" },
    { emoji: "🍏", keywords: "green apple" },
    { emoji: "🍐", keywords: "pear" },
    { emoji: "🍑", keywords: "peach" },
    { emoji: "🍒", keywords: "cherries" },
    { emoji: "🍓", keywords: "strawberry" },
    { emoji: "🫐", keywords: "blueberries" },
    { emoji: "🥝", keywords: "kiwi fruit" },
    { emoji: "🍅", keywords: "tomato" },
    { emoji: "🫒", keywords: "olive" },
    { emoji: "🥥", keywords: "coconut" },
    { emoji: "🥑", keywords: "avocado" },
    { emoji: "🍆", keywords: "eggplant" },
    { emoji: "🥔", keywords: "potato" },
    { emoji: "🥕", keywords: "carrot" },
    { emoji: "🌽", keywords: "ear of corn" },
    { emoji: "🌶️", keywords: "hot pepper" },
    { emoji: "🫑", keywords: "bell pepper" },
    { emoji: "🥒", keywords: "cucumber" },
    { emoji: "🥬", keywords: "leafy green" },
    { emoji: "🥦", keywords: "broccoli" },
    { emoji: "🧄", keywords: "garlic" },
    { emoji: "🧅", keywords: "onion" },
    { emoji: "🥜", keywords: "peanuts" },
    { emoji: "🫘", keywords: "beans" },
    { emoji: "🌰", keywords: "chestnut" },
    { emoji: "🫚", keywords: "ginger root" },
    { emoji: "🫛", keywords: "pea pod" },
    { emoji: "🍄‍🟫", keywords: "brown mushroom" },
    { emoji: "🫜", keywords: "root vegetable" },
    { emoji: "🍞", keywords: "bread" },
    { emoji: "🥐", keywords: "croissant" },
    { emoji: "🥖", keywords: "baguette bread" },
    { emoji: "🫓", keywords: "flatbread" },
    { emoji: "🥨", keywords: "pretzel" },
    { emoji: "🥯", keywords: "bagel" },
    { emoji: "🥞", keywords: "pancakes" },
    { emoji: "🧇", keywords: "waffle" },
    { emoji: "🧀", keywords: "cheese wedge" },
    { emoji: "🍖", keywords: "meat on bone" },
    { emoji: "🍗", keywords: "poultry leg" },
    { emoji: "🥩", keywords: "cut of meat" },
    { emoji: "🥓", keywords: "bacon" },
    { emoji: "🍔", keywords: "hamburger" },
    { emoji: "🍟", keywords: "french fries" },
    { emoji: "🍕", keywords: "pizza" },
    { emoji: "🌭", keywords: "hot dog" },
    { emoji: "🥪", keywords: "sandwich" },
    { emoji: "🌮", keywords: "taco" },
    { emoji: "🌯", keywords: "burrito" },
    { emoji: "🫔", keywords: "tamale" },
    { emoji: "🥙", keywords: "stuffed flatbread" },
    { emoji: "🧆", keywords: "falafel" },
    { emoji: "🥚", keywords: "egg" },
    { emoji: "🍳", keywords: "cooking" },
    { emoji: "🥘", keywords: "shallow pan of food" },
    { emoji: "🍲", keywords: "pot of food" },
    { emoji: "🫕", keywords: "fondue" },
    { emoji: "🥣", keywords: "bowl with spoon" },
    { emoji: "🥗", keywords: "green salad" },
    { emoji: "🍿", keywords: "popcorn" },
    { emoji: "🧈", keywords: "butter" },
    { emoji: "🧂", keywords: "salt" },
    { emoji: "🥫", keywords: "canned food" },
    { emoji: "🍱", keywords: "bento box" },
    { emoji: "🍘", keywords: "rice cracker" },
    { emoji: "🍙", keywords: "rice ball" },
    { emoji: "🍚", keywords: "cooked rice" },
    { emoji: "🍛", keywords: "curry rice" },
    { emoji: "🍜", keywords: "steaming bowl" },
    { emoji: "🍝", keywords: "spaghetti" },
    { emoji: "🍠", keywords: "roasted sweet potato" },
    { emoji: "🍢", keywords: "oden" },
    { emoji: "🍣", keywords: "sushi" },
    { emoji: "🍤", keywords: "fried shrimp" },
    { emoji: "🍥", keywords: "fish cake with swirl" },
    { emoji: "🥮", keywords: "moon cake" },
    { emoji: "🍡", keywords: "dango" },
    { emoji: "🥟", keywords: "dumpling" },
    { emoji: "🥠", keywords: "fortune cookie" },
    { emoji: "🥡", keywords: "takeout box" },
    { emoji: "🍦", keywords: "soft ice cream" },
    { emoji: "🍧", keywords: "shaved ice" },
    { emoji: "🍨", keywords: "ice cream" },
    { emoji: "🍩", keywords: "doughnut" },
    { emoji: "🍪", keywords: "cookie" },
    { emoji: "🎂", keywords: "birthday cake" },
    { emoji: "🍰", keywords: "shortcake" },
    { emoji: "🧁", keywords: "cupcake" },
    { emoji: "🥧", keywords: "pie" },
    { emoji: "🍫", keywords: "chocolate bar" },
    { emoji: "🍬", keywords: "candy" },
    { emoji: "🍭", keywords: "lollipop" },
    { emoji: "🍮", keywords: "custard" },
    { emoji: "🍯", keywords: "honey pot" },
    { emoji: "🍼", keywords: "baby bottle" },
    { emoji: "🥛", keywords: "glass of milk" },
    { emoji: "☕", keywords: "hot beverage" },
    { emoji: "🫖", keywords: "teapot" },
    { emoji: "🍵", keywords: "teacup without handle" },
    { emoji: "🍶", keywords: "sake" },
    { emoji: "🍾", keywords: "bottle with popping cork" },
    { emoji: "🍷", keywords: "wine glass" },
    { emoji: "🍸", keywords: "cocktail glass" },
    { emoji: "🍹", keywords: "tropical drink" },
    { emoji: "🍺", keywords: "beer mug" },
    { emoji: "🍻", keywords: "clinking beer mugs" },
    { emoji: "🥂", keywords: "clinking glasses" },
    { emoji: "🥃", keywords: "tumbler glass" },
    { emoji: "🫗", keywords: "pouring liquid" },
    { emoji: "🥤", keywords: "cup with straw" },
    { emoji: "🧋", keywords: "bubble tea" },
    { emoji: "🧃", keywords: "beverage box" },
    { emoji: "🧉", keywords: "mate" },
    { emoji: "🧊", keywords: "ice" },
    { emoji: "🥢", keywords: "chopsticks" },
    { emoji: "🍽️", keywords: "fork and knife with plate" },
    { emoji: "🍴", keywords: "fork and knife" },
    { emoji: "🥄", keywords: "spoon" },
    { emoji: "🔪", keywords: "kitchen knife" },
    { emoji: "🫙", keywords: "jar" },
    { emoji: "🏺", keywords: "amphora" },
    ],
  },
  {
    name: "Travel & Places",
    emojis: [
    { emoji: "🌍", keywords: "globe showing europe africa" },
    { emoji: "🌎", keywords: "globe showing americas" },
    { emoji: "🌏", keywords: "globe showing asia australia" },
    { emoji: "🌐", keywords: "globe with meridians" },
    { emoji: "🗺️", keywords: "world map" },
    { emoji: "🗾", keywords: "map of japan" },
    { emoji: "🧭", keywords: "compass" },
    { emoji: "🏔️", keywords: "snow capped mountain" },
    { emoji: "⛰️", keywords: "mountain" },
    { emoji: "🌋", keywords: "volcano" },
    { emoji: "🗻", keywords: "mount fuji" },
    { emoji: "🏕️", keywords: "camping" },
    { emoji: "🏖️", keywords: "beach with umbrella" },
    { emoji: "🏜️", keywords: "desert" },
    { emoji: "🏝️", keywords: "desert island" },
    { emoji: "🏞️", keywords: "national park" },
    { emoji: "🏟️", keywords: "stadium" },
    { emoji: "🏛️", keywords: "classical building" },
    { emoji: "🏗️", keywords: "building construction" },
    { emoji: "🧱", keywords: "brick" },
    { emoji: "🪨", keywords: "rock" },
    { emoji: "🪵", keywords: "wood" },
    { emoji: "🛖", keywords: "hut" },
    { emoji: "🏘️", keywords: "houses" },
    { emoji: "🏚️", keywords: "derelict house" },
    { emoji: "🏠", keywords: "house" },
    { emoji: "🏡", keywords: "house with garden" },
    { emoji: "🏢", keywords: "office building" },
    { emoji: "🏣", keywords: "japanese post office" },
    { emoji: "🏤", keywords: "post office" },
    { emoji: "🏥", keywords: "hospital" },
    { emoji: "🏦", keywords: "bank" },
    { emoji: "🏨", keywords: "hotel" },
    { emoji: "🏩", keywords: "love hotel" },
    { emoji: "🏪", keywords: "convenience store" },
    { emoji: "🏫", keywords: "school" },
    { emoji: "🏬", keywords: "department store" },
    { emoji: "🏭", keywords: "factory" },
    { emoji: "🏯", keywords: "japanese castle" },
    { emoji: "🏰", keywords: "castle" },
    { emoji: "💒", keywords: "wedding" },
    { emoji: "🗼", keywords: "tokyo tower" },
    { emoji: "🗽", keywords: "statue of liberty" },
    { emoji: "⛪", keywords: "church" },
    { emoji: "🕌", keywords: "mosque" },
    { emoji: "🛕", keywords: "hindu temple" },
    { emoji: "🕍", keywords: "synagogue" },
    { emoji: "⛩️", keywords: "shinto shrine" },
    { emoji: "🕋", keywords: "kaaba" },
    { emoji: "⛲", keywords: "fountain" },
    { emoji: "⛺", keywords: "tent" },
    { emoji: "🌁", keywords: "foggy" },
    { emoji: "🌃", keywords: "night with stars" },
    { emoji: "🏙️", keywords: "cityscape" },
    { emoji: "🌄", keywords: "sunrise over mountains" },
    { emoji: "🌅", keywords: "sunrise" },
    { emoji: "🌆", keywords: "cityscape at dusk" },
    { emoji: "🌇", keywords: "sunset" },
    { emoji: "🌉", keywords: "bridge at night" },
    { emoji: "♨️", keywords: "hot springs" },
    { emoji: "🎠", keywords: "carousel horse" },
    { emoji: "🛝", keywords: "playground slide" },
    { emoji: "🎡", keywords: "ferris wheel" },
    { emoji: "🎢", keywords: "roller coaster" },
    { emoji: "💈", keywords: "barber pole" },
    { emoji: "🎪", keywords: "circus tent" },
    { emoji: "🚂", keywords: "locomotive" },
    { emoji: "🚃", keywords: "railway car" },
    { emoji: "🚄", keywords: "high speed train" },
    { emoji: "🚅", keywords: "bullet train" },
    { emoji: "🚆", keywords: "train" },
    { emoji: "🚇", keywords: "metro" },
    { emoji: "🚈", keywords: "light rail" },
    { emoji: "🚉", keywords: "station" },
    { emoji: "🚊", keywords: "tram" },
    { emoji: "🚝", keywords: "monorail" },
    { emoji: "🚞", keywords: "mountain railway" },
    { emoji: "🚋", keywords: "tram car" },
    { emoji: "🚌", keywords: "bus" },
    { emoji: "🚍", keywords: "oncoming bus" },
    { emoji: "🚎", keywords: "trolleybus" },
    { emoji: "🚐", keywords: "minibus" },
    { emoji: "🚑", keywords: "ambulance" },
    { emoji: "🚒", keywords: "fire engine" },
    { emoji: "🚓", keywords: "police car" },
    { emoji: "🚔", keywords: "oncoming police car" },
    { emoji: "🚕", keywords: "taxi" },
    { emoji: "🚖", keywords: "oncoming taxi" },
    { emoji: "🚗", keywords: "automobile" },
    { emoji: "🚘", keywords: "oncoming automobile" },
    { emoji: "🚙", keywords: "sport utility vehicle" },
    { emoji: "🛻", keywords: "pickup truck" },
    { emoji: "🚚", keywords: "delivery truck" },
    { emoji: "🚛", keywords: "articulated lorry" },
    { emoji: "🚜", keywords: "tractor" },
    { emoji: "🏎️", keywords: "racing car" },
    { emoji: "🏍️", keywords: "motorcycle" },
    { emoji: "🛵", keywords: "motor scooter" },
    { emoji: "🦽", keywords: "manual wheelchair" },
    { emoji: "🦼", keywords: "motorized wheelchair" },
    { emoji: "🛺", keywords: "auto rickshaw" },
    { emoji: "🚲", keywords: "bicycle" },
    { emoji: "🛴", keywords: "kick scooter" },
    { emoji: "🛹", keywords: "skateboard" },
    { emoji: "🛼", keywords: "roller skate" },
    { emoji: "🚏", keywords: "bus stop" },
    { emoji: "🛣️", keywords: "motorway" },
    { emoji: "🛤️", keywords: "railway track" },
    { emoji: "🛢️", keywords: "oil drum" },
    { emoji: "⛽", keywords: "fuel pump" },
    { emoji: "🛞", keywords: "wheel" },
    { emoji: "🚨", keywords: "police car light" },
    { emoji: "🚥", keywords: "horizontal traffic light" },
    { emoji: "🚦", keywords: "vertical traffic light" },
    { emoji: "🛑", keywords: "stop sign" },
    { emoji: "🚧", keywords: "construction" },
    { emoji: "⚓", keywords: "anchor" },
    { emoji: "🛟", keywords: "ring buoy" },
    { emoji: "⛵", keywords: "sailboat" },
    { emoji: "🛶", keywords: "canoe" },
    { emoji: "🚤", keywords: "speedboat" },
    { emoji: "🛳️", keywords: "passenger ship" },
    { emoji: "⛴️", keywords: "ferry" },
    { emoji: "🛥️", keywords: "motor boat" },
    { emoji: "🚢", keywords: "ship" },
    { emoji: "✈️", keywords: "airplane" },
    { emoji: "🛩️", keywords: "small airplane" },
    { emoji: "🛫", keywords: "airplane departure" },
    { emoji: "🛬", keywords: "airplane arrival" },
    { emoji: "🪂", keywords: "parachute" },
    { emoji: "💺", keywords: "seat" },
    { emoji: "🚁", keywords: "helicopter" },
    { emoji: "🚟", keywords: "suspension railway" },
    { emoji: "🚠", keywords: "mountain cableway" },
    { emoji: "🚡", keywords: "aerial tramway" },
    { emoji: "🛰️", keywords: "satellite" },
    { emoji: "🚀", keywords: "rocket" },
    { emoji: "🛸", keywords: "flying saucer" },
    { emoji: "🛎️", keywords: "bellhop bell" },
    { emoji: "🧳", keywords: "luggage" },
    { emoji: "⌛", keywords: "hourglass done" },
    { emoji: "⏳", keywords: "hourglass not done" },
    { emoji: "⌚", keywords: "watch" },
    { emoji: "⏰", keywords: "alarm clock" },
    { emoji: "⏱️", keywords: "stopwatch" },
    { emoji: "⏲️", keywords: "timer clock" },
    { emoji: "🕰️", keywords: "mantelpiece clock" },
    { emoji: "🕛", keywords: "twelve o clock" },
    { emoji: "🕧", keywords: "twelve thirty" },
    { emoji: "🕐", keywords: "one o clock" },
    { emoji: "🕜", keywords: "one thirty" },
    { emoji: "🕑", keywords: "two o clock" },
    { emoji: "🕝", keywords: "two thirty" },
    { emoji: "🕒", keywords: "three o clock" },
    { emoji: "🕞", keywords: "three thirty" },
    { emoji: "🕓", keywords: "four o clock" },
    { emoji: "🕟", keywords: "four thirty" },
    { emoji: "🕔", keywords: "five o clock" },
    { emoji: "🕠", keywords: "five thirty" },
    { emoji: "🕕", keywords: "six o clock" },
    { emoji: "🕡", keywords: "six thirty" },
    { emoji: "🕖", keywords: "seven o clock" },
    { emoji: "🕢", keywords: "seven thirty" },
    { emoji: "🕗", keywords: "eight o clock" },
    { emoji: "🕣", keywords: "eight thirty" },
    { emoji: "🕘", keywords: "nine o clock" },
    { emoji: "🕤", keywords: "nine thirty" },
    { emoji: "🕙", keywords: "ten o clock" },
    { emoji: "🕥", keywords: "ten thirty" },
    { emoji: "🕚", keywords: "eleven o clock" },
    { emoji: "🕦", keywords: "eleven thirty" },
    { emoji: "🌑", keywords: "new moon" },
    { emoji: "🌒", keywords: "waxing crescent moon" },
    { emoji: "🌓", keywords: "first quarter moon" },
    { emoji: "🌔", keywords: "waxing gibbous moon" },
    { emoji: "🌕", keywords: "full moon" },
    { emoji: "🌖", keywords: "waning gibbous moon" },
    { emoji: "🌗", keywords: "last quarter moon" },
    { emoji: "🌘", keywords: "waning crescent moon" },
    { emoji: "🌙", keywords: "crescent moon" },
    { emoji: "🌚", keywords: "new moon face" },
    { emoji: "🌛", keywords: "first quarter moon face" },
    { emoji: "🌜", keywords: "last quarter moon face" },
    { emoji: "🌡️", keywords: "thermometer" },
    { emoji: "☀️", keywords: "sun" },
    { emoji: "🌝", keywords: "full moon face" },
    { emoji: "🌞", keywords: "sun with face" },
    { emoji: "🪐", keywords: "ringed planet" },
    { emoji: "⭐", keywords: "star" },
    { emoji: "🌟", keywords: "glowing star" },
    { emoji: "🌠", keywords: "shooting star" },
    { emoji: "🌌", keywords: "milky way" },
    { emoji: "☁️", keywords: "cloud" },
    { emoji: "⛅", keywords: "sun behind cloud" },
    { emoji: "⛈️", keywords: "cloud with lightning and rain" },
    { emoji: "🌤️", keywords: "sun behind small cloud" },
    { emoji: "🌥️", keywords: "sun behind large cloud" },
    { emoji: "🌦️", keywords: "sun behind rain cloud" },
    { emoji: "🌧️", keywords: "cloud with rain" },
    { emoji: "🌨️", keywords: "cloud with snow" },
    { emoji: "🌩️", keywords: "cloud with lightning" },
    { emoji: "🌪️", keywords: "tornado" },
    { emoji: "🌫️", keywords: "fog" },
    { emoji: "🌬️", keywords: "wind face" },
    { emoji: "🌀", keywords: "cyclone" },
    { emoji: "🌈", keywords: "rainbow" },
    { emoji: "🌂", keywords: "closed umbrella" },
    { emoji: "☂️", keywords: "umbrella" },
    { emoji: "☔", keywords: "umbrella with rain drops" },
    { emoji: "⛱️", keywords: "umbrella on ground" },
    { emoji: "⚡", keywords: "high voltage" },
    { emoji: "❄️", keywords: "snowflake" },
    { emoji: "☃️", keywords: "snowman" },
    { emoji: "⛄", keywords: "snowman without snow" },
    { emoji: "☄️", keywords: "comet" },
    { emoji: "🔥", keywords: "fire" },
    { emoji: "💧", keywords: "droplet" },
    { emoji: "🌊", keywords: "water wave" },
    ],
  },
  {
    name: "Activities",
    emojis: [
    { emoji: "🎃", keywords: "jack o lantern" },
    { emoji: "🎄", keywords: "christmas tree" },
    { emoji: "🎆", keywords: "fireworks" },
    { emoji: "🎇", keywords: "sparkler" },
    { emoji: "🧨", keywords: "firecracker" },
    { emoji: "✨", keywords: "sparkles" },
    { emoji: "🎈", keywords: "balloon" },
    { emoji: "🎉", keywords: "party popper" },
    { emoji: "🎊", keywords: "confetti ball" },
    { emoji: "🎋", keywords: "tanabata tree" },
    { emoji: "🎍", keywords: "pine decoration" },
    { emoji: "🎎", keywords: "japanese dolls" },
    { emoji: "🎏", keywords: "carp streamer" },
    { emoji: "🎐", keywords: "wind chime" },
    { emoji: "🎑", keywords: "moon viewing ceremony" },
    { emoji: "🧧", keywords: "red envelope" },
    { emoji: "🎀", keywords: "ribbon" },
    { emoji: "🎁", keywords: "wrapped gift" },
    { emoji: "🎗️", keywords: "reminder ribbon" },
    { emoji: "🎟️", keywords: "admission tickets" },
    { emoji: "🎫", keywords: "ticket" },
    { emoji: "🎖️", keywords: "military medal" },
    { emoji: "🏆", keywords: "trophy" },
    { emoji: "🏅", keywords: "sports medal" },
    { emoji: "🥇", keywords: "1st place medal" },
    { emoji: "🥈", keywords: "2nd place medal" },
    { emoji: "🥉", keywords: "3rd place medal" },
    { emoji: "⚽", keywords: "soccer ball" },
    { emoji: "⚾", keywords: "baseball" },
    { emoji: "🥎", keywords: "softball" },
    { emoji: "🏀", keywords: "basketball" },
    { emoji: "🏐", keywords: "volleyball" },
    { emoji: "🏈", keywords: "american football" },
    { emoji: "🏉", keywords: "rugby football" },
    { emoji: "🎾", keywords: "tennis" },
    { emoji: "🥏", keywords: "flying disc" },
    { emoji: "🎳", keywords: "bowling" },
    { emoji: "🏏", keywords: "cricket game" },
    { emoji: "🏑", keywords: "field hockey" },
    { emoji: "🏒", keywords: "ice hockey" },
    { emoji: "🥍", keywords: "lacrosse" },
    { emoji: "🏓", keywords: "ping pong" },
    { emoji: "🏸", keywords: "badminton" },
    { emoji: "🥊", keywords: "boxing glove" },
    { emoji: "🥋", keywords: "martial arts uniform" },
    { emoji: "🥅", keywords: "goal net" },
    { emoji: "⛳", keywords: "flag in hole" },
    { emoji: "⛸️", keywords: "ice skate" },
    { emoji: "🎣", keywords: "fishing pole" },
    { emoji: "🤿", keywords: "diving mask" },
    { emoji: "🎽", keywords: "running shirt" },
    { emoji: "🎿", keywords: "skis" },
    { emoji: "🛷", keywords: "sled" },
    { emoji: "🥌", keywords: "curling stone" },
    { emoji: "🎯", keywords: "bullseye" },
    { emoji: "🪀", keywords: "yo" },
    { emoji: "🪁", keywords: "kite" },
    { emoji: "🔫", keywords: "water pistol" },
    { emoji: "🎱", keywords: "pool 8 ball" },
    { emoji: "🔮", keywords: "crystal ball" },
    { emoji: "🪄", keywords: "magic wand" },
    { emoji: "🎮", keywords: "video game" },
    { emoji: "🕹️", keywords: "joystick" },
    { emoji: "🎰", keywords: "slot machine" },
    { emoji: "🎲", keywords: "game die" },
    { emoji: "🧩", keywords: "puzzle piece" },
    { emoji: "🧸", keywords: "teddy bear" },
    { emoji: "🪅", keywords: "pi ata pinata" },
    { emoji: "🪩", keywords: "mirror ball" },
    { emoji: "🪆", keywords: "nesting dolls" },
    { emoji: "♠️", keywords: "spade suit" },
    { emoji: "♥️", keywords: "heart suit" },
    { emoji: "♦️", keywords: "diamond suit" },
    { emoji: "♣️", keywords: "club suit" },
    { emoji: "♟️", keywords: "chess pawn" },
    { emoji: "🃏", keywords: "joker" },
    { emoji: "🀄", keywords: "mahjong red dragon" },
    { emoji: "🎴", keywords: "flower playing cards" },
    { emoji: "🎭", keywords: "performing arts" },
    { emoji: "🖼️", keywords: "framed picture" },
    { emoji: "🎨", keywords: "artist palette" },
    { emoji: "🧵", keywords: "thread" },
    { emoji: "🪡", keywords: "sewing needle" },
    { emoji: "🧶", keywords: "yarn" },
    { emoji: "🪢", keywords: "knot" },
    ],
  },
  {
    name: "Objects",
    emojis: [
    { emoji: "👓", keywords: "glasses" },
    { emoji: "🕶️", keywords: "sunglasses" },
    { emoji: "🥽", keywords: "goggles" },
    { emoji: "🥼", keywords: "lab coat" },
    { emoji: "🦺", keywords: "safety vest" },
    { emoji: "👔", keywords: "necktie" },
    { emoji: "👕", keywords: "t shirt" },
    { emoji: "👖", keywords: "jeans" },
    { emoji: "🧣", keywords: "scarf" },
    { emoji: "🧤", keywords: "gloves" },
    { emoji: "🧥", keywords: "coat" },
    { emoji: "🧦", keywords: "socks" },
    { emoji: "👗", keywords: "dress" },
    { emoji: "👘", keywords: "kimono" },
    { emoji: "🥻", keywords: "sari" },
    { emoji: "🩱", keywords: "one piece swimsuit" },
    { emoji: "🩲", keywords: "briefs" },
    { emoji: "🩳", keywords: "shorts" },
    { emoji: "👙", keywords: "bikini" },
    { emoji: "👚", keywords: "woman s clothes" },
    { emoji: "🪭", keywords: "folding hand fan" },
    { emoji: "👛", keywords: "purse" },
    { emoji: "👜", keywords: "handbag" },
    { emoji: "👝", keywords: "clutch bag" },
    { emoji: "🛍️", keywords: "shopping bags" },
    { emoji: "🎒", keywords: "backpack" },
    { emoji: "🩴", keywords: "thong sandal" },
    { emoji: "👞", keywords: "man s shoe" },
    { emoji: "👟", keywords: "running shoe" },
    { emoji: "🥾", keywords: "hiking boot" },
    { emoji: "🥿", keywords: "flat shoe" },
    { emoji: "👠", keywords: "high heeled shoe" },
    { emoji: "👡", keywords: "woman s sandal" },
    { emoji: "🩰", keywords: "ballet shoes" },
    { emoji: "👢", keywords: "woman s boot" },
    { emoji: "🪮", keywords: "hair pick" },
    { emoji: "👑", keywords: "crown" },
    { emoji: "👒", keywords: "woman s hat" },
    { emoji: "🎩", keywords: "top hat" },
    { emoji: "🎓", keywords: "graduation cap" },
    { emoji: "🧢", keywords: "billed cap" },
    { emoji: "🪖", keywords: "military helmet" },
    { emoji: "⛑️", keywords: "rescue worker s helmet" },
    { emoji: "📿", keywords: "prayer beads" },
    { emoji: "💄", keywords: "lipstick" },
    { emoji: "💍", keywords: "ring" },
    { emoji: "💎", keywords: "gem stone" },
    { emoji: "🔇", keywords: "muted speaker" },
    { emoji: "🔈", keywords: "speaker low volume" },
    { emoji: "🔉", keywords: "speaker medium volume" },
    { emoji: "🔊", keywords: "speaker high volume" },
    { emoji: "📢", keywords: "loudspeaker" },
    { emoji: "📣", keywords: "megaphone" },
    { emoji: "📯", keywords: "postal horn" },
    { emoji: "🔔", keywords: "bell" },
    { emoji: "🔕", keywords: "bell with slash" },
    { emoji: "🎼", keywords: "musical score" },
    { emoji: "🎵", keywords: "musical note" },
    { emoji: "🎶", keywords: "musical notes" },
    { emoji: "🎙️", keywords: "studio microphone" },
    { emoji: "🎚️", keywords: "level slider" },
    { emoji: "🎛️", keywords: "control knobs" },
    { emoji: "🎤", keywords: "microphone" },
    { emoji: "🎧", keywords: "headphone" },
    { emoji: "📻", keywords: "radio" },
    { emoji: "🎷", keywords: "saxophone" },
    { emoji: "🪗", keywords: "accordion" },
    { emoji: "🎸", keywords: "guitar" },
    { emoji: "🎹", keywords: "musical keyboard" },
    { emoji: "🎺", keywords: "trumpet" },
    { emoji: "🎻", keywords: "violin" },
    { emoji: "🪕", keywords: "banjo" },
    { emoji: "🥁", keywords: "drum" },
    { emoji: "🪘", keywords: "long drum" },
    { emoji: "🪇", keywords: "maracas" },
    { emoji: "🪈", keywords: "flute" },
    { emoji: "🪉", keywords: "harp" },
    { emoji: "📱", keywords: "mobile phone" },
    { emoji: "📲", keywords: "mobile phone with arrow" },
    { emoji: "☎️", keywords: "telephone" },
    { emoji: "📞", keywords: "telephone receiver" },
    { emoji: "📟", keywords: "pager" },
    { emoji: "📠", keywords: "fax machine" },
    { emoji: "🔋", keywords: "battery" },
    { emoji: "🪫", keywords: "low battery" },
    { emoji: "🔌", keywords: "electric plug" },
    { emoji: "💻", keywords: "laptop" },
    { emoji: "🖥️", keywords: "desktop computer" },
    { emoji: "🖨️", keywords: "printer" },
    { emoji: "⌨️", keywords: "keyboard" },
    { emoji: "🖱️", keywords: "computer mouse" },
    { emoji: "🖲️", keywords: "trackball" },
    { emoji: "💽", keywords: "computer disk" },
    { emoji: "💾", keywords: "floppy disk" },
    { emoji: "💿", keywords: "optical disk" },
    { emoji: "📀", keywords: "dvd" },
    { emoji: "🧮", keywords: "abacus" },
    { emoji: "🎥", keywords: "movie camera" },
    { emoji: "🎞️", keywords: "film frames" },
    { emoji: "📽️", keywords: "film projector" },
    { emoji: "🎬", keywords: "clapper board" },
    { emoji: "📺", keywords: "television" },
    { emoji: "📷", keywords: "camera" },
    { emoji: "📸", keywords: "camera with flash" },
    { emoji: "📹", keywords: "video camera" },
    { emoji: "📼", keywords: "videocassette" },
    { emoji: "🔍", keywords: "magnifying glass tilted left" },
    { emoji: "🔎", keywords: "magnifying glass tilted right" },
    { emoji: "🕯️", keywords: "candle" },
    { emoji: "💡", keywords: "light bulb" },
    { emoji: "🔦", keywords: "flashlight" },
    { emoji: "🏮", keywords: "red paper lantern" },
    { emoji: "🪔", keywords: "diya lamp" },
    { emoji: "📔", keywords: "notebook with decorative cover" },
    { emoji: "📕", keywords: "closed book" },
    { emoji: "📖", keywords: "open book" },
    { emoji: "📗", keywords: "green book" },
    { emoji: "📘", keywords: "blue book" },
    { emoji: "📙", keywords: "orange book" },
    { emoji: "📚", keywords: "books" },
    { emoji: "📓", keywords: "notebook" },
    { emoji: "📒", keywords: "ledger" },
    { emoji: "📃", keywords: "page with curl" },
    { emoji: "📜", keywords: "scroll" },
    { emoji: "📄", keywords: "page facing up" },
    { emoji: "📰", keywords: "newspaper" },
    { emoji: "🗞️", keywords: "rolled up newspaper" },
    { emoji: "📑", keywords: "bookmark tabs" },
    { emoji: "🔖", keywords: "bookmark" },
    { emoji: "🏷️", keywords: "label" },
    { emoji: "💰", keywords: "money bag" },
    { emoji: "🪙", keywords: "coin" },
    { emoji: "💴", keywords: "yen banknote" },
    { emoji: "💵", keywords: "dollar banknote" },
    { emoji: "💶", keywords: "euro banknote" },
    { emoji: "💷", keywords: "pound banknote" },
    { emoji: "💸", keywords: "money with wings" },
    { emoji: "💳", keywords: "credit card" },
    { emoji: "🧾", keywords: "receipt" },
    { emoji: "💹", keywords: "chart increasing with yen" },
    { emoji: "✉️", keywords: "envelope" },
    { emoji: "📧", keywords: "e mail" },
    { emoji: "📨", keywords: "incoming envelope" },
    { emoji: "📩", keywords: "envelope with arrow" },
    { emoji: "📤", keywords: "outbox tray" },
    { emoji: "📥", keywords: "inbox tray" },
    { emoji: "📦", keywords: "package" },
    { emoji: "📫", keywords: "closed mailbox with raised flag" },
    { emoji: "📪", keywords: "closed mailbox with lowered flag" },
    { emoji: "📬", keywords: "open mailbox with raised flag" },
    { emoji: "📭", keywords: "open mailbox with lowered flag" },
    { emoji: "📮", keywords: "postbox" },
    { emoji: "🗳️", keywords: "ballot box with" },
    { emoji: "✏️", keywords: "pencil" },
    { emoji: "✒️", keywords: "black nib" },
    { emoji: "🖋️", keywords: "fountain pen" },
    { emoji: "🖊️", keywords: "pen" },
    { emoji: "🖌️", keywords: "paintbrush" },
    { emoji: "🖍️", keywords: "crayon" },
    { emoji: "📝", keywords: "memo" },
    { emoji: "💼", keywords: "briefcase" },
    { emoji: "📁", keywords: "file folder" },
    { emoji: "📂", keywords: "open file folder" },
    { emoji: "🗂️", keywords: "card index dividers" },
    { emoji: "📅", keywords: "calendar" },
    { emoji: "📆", keywords: "tear off calendar" },
    { emoji: "🗒️", keywords: "spiral notepad" },
    { emoji: "🗓️", keywords: "spiral calendar" },
    { emoji: "📇", keywords: "card index" },
    { emoji: "📈", keywords: "chart increasing" },
    { emoji: "📉", keywords: "chart decreasing" },
    { emoji: "📊", keywords: "bar chart" },
    { emoji: "📋", keywords: "clipboard" },
    { emoji: "📌", keywords: "pushpin" },
    { emoji: "📍", keywords: "round pushpin" },
    { emoji: "📎", keywords: "paperclip" },
    { emoji: "🖇️", keywords: "linked paperclips" },
    { emoji: "📏", keywords: "straight ruler" },
    { emoji: "📐", keywords: "triangular ruler" },
    { emoji: "✂️", keywords: "scissors" },
    { emoji: "🗃️", keywords: "card file box" },
    { emoji: "🗄️", keywords: "file cabinet" },
    { emoji: "🗑️", keywords: "wastebasket" },
    { emoji: "🔒", keywords: "locked" },
    { emoji: "🔓", keywords: "unlocked" },
    { emoji: "🔏", keywords: "locked with pen" },
    { emoji: "🔐", keywords: "locked with key" },
    { emoji: "🔑", keywords: "key" },
    { emoji: "🗝️", keywords: "old key" },
    { emoji: "🔨", keywords: "hammer" },
    { emoji: "🪓", keywords: "axe" },
    { emoji: "⛏️", keywords: "pick" },
    { emoji: "⚒️", keywords: "hammer and pick" },
    { emoji: "🛠️", keywords: "hammer and wrench" },
    { emoji: "🗡️", keywords: "dagger" },
    { emoji: "⚔️", keywords: "crossed swords" },
    { emoji: "💣", keywords: "bomb" },
    { emoji: "🪃", keywords: "boomerang" },
    { emoji: "🏹", keywords: "bow and arrow" },
    { emoji: "🛡️", keywords: "shield" },
    { emoji: "🪚", keywords: "carpentry saw" },
    { emoji: "🔧", keywords: "wrench" },
    { emoji: "🪛", keywords: "screwdriver" },
    { emoji: "🔩", keywords: "nut and bolt" },
    { emoji: "⚙️", keywords: "gear" },
    { emoji: "🗜️", keywords: "clamp" },
    { emoji: "⚖️", keywords: "balance scale" },
    { emoji: "🦯", keywords: "white cane" },
    { emoji: "🔗", keywords: "link" },
    { emoji: "⛓️‍💥", keywords: "broken chain" },
    { emoji: "⛓️", keywords: "chains" },
    { emoji: "🪝", keywords: "hook" },
    { emoji: "🧰", keywords: "toolbox" },
    { emoji: "🧲", keywords: "magnet" },
    { emoji: "🪜", keywords: "ladder" },
    { emoji: "🪏", keywords: "shovel" },
    { emoji: "⚗️", keywords: "alembic" },
    { emoji: "🧪", keywords: "test tube" },
    { emoji: "🧫", keywords: "petri dish" },
    { emoji: "🧬", keywords: "dna" },
    { emoji: "🔬", keywords: "microscope" },
    { emoji: "🔭", keywords: "telescope" },
    { emoji: "📡", keywords: "satellite antenna" },
    { emoji: "💉", keywords: "syringe" },
    { emoji: "🩸", keywords: "drop of blood" },
    { emoji: "💊", keywords: "pill" },
    { emoji: "🩹", keywords: "adhesive bandage" },
    { emoji: "🩼", keywords: "crutch" },
    { emoji: "🩺", keywords: "stethoscope" },
    { emoji: "🩻", keywords: "x ray" },
    { emoji: "🚪", keywords: "door" },
    { emoji: "🛗", keywords: "elevator" },
    { emoji: "🪞", keywords: "mirror" },
    { emoji: "🪟", keywords: "window" },
    { emoji: "🛏️", keywords: "bed" },
    { emoji: "🛋️", keywords: "couch and lamp" },
    { emoji: "🪑", keywords: "chair" },
    { emoji: "🚽", keywords: "toilet" },
    { emoji: "🪠", keywords: "plunger" },
    { emoji: "🚿", keywords: "shower" },
    { emoji: "🛁", keywords: "bathtub" },
    { emoji: "🪤", keywords: "mouse trap" },
    { emoji: "🪒", keywords: "razor" },
    { emoji: "🧴", keywords: "lotion bottle" },
    { emoji: "🧷", keywords: "safety pin" },
    { emoji: "🧹", keywords: "broom" },
    { emoji: "🧺", keywords: "basket" },
    { emoji: "🧻", keywords: "roll of paper" },
    { emoji: "🪣", keywords: "bucket" },
    { emoji: "🧼", keywords: "soap" },
    { emoji: "🫧", keywords: "bubbles" },
    { emoji: "🪥", keywords: "toothbrush" },
    { emoji: "🧽", keywords: "sponge" },
    { emoji: "🧯", keywords: "fire extinguisher" },
    { emoji: "🛒", keywords: "shopping cart" },
    { emoji: "🚬", keywords: "cigarette" },
    { emoji: "⚰️", keywords: "coffin" },
    { emoji: "🪦", keywords: "headstone" },
    { emoji: "⚱️", keywords: "funeral urn" },
    { emoji: "🧿", keywords: "nazar amulet" },
    { emoji: "🪬", keywords: "hamsa" },
    { emoji: "🗿", keywords: "moai" },
    { emoji: "🪧", keywords: "placard" },
    { emoji: "🪪", keywords: "identification card" },
    ],
  },
  {
    name: "Symbols",
    emojis: [
    { emoji: "🏧", keywords: "atm sign" },
    { emoji: "🚮", keywords: "litter in bin sign" },
    { emoji: "🚰", keywords: "potable water" },
    { emoji: "♿", keywords: "wheelchair symbol" },
    { emoji: "🚹", keywords: "men s room" },
    { emoji: "🚺", keywords: "women s room" },
    { emoji: "🚻", keywords: "restroom" },
    { emoji: "🚼", keywords: "baby symbol" },
    { emoji: "🚾", keywords: "water closet" },
    { emoji: "🛂", keywords: "passport control" },
    { emoji: "🛃", keywords: "customs" },
    { emoji: "🛄", keywords: "baggage claim" },
    { emoji: "🛅", keywords: "left luggage" },
    { emoji: "⚠️", keywords: "warning" },
    { emoji: "🚸", keywords: "children crossing" },
    { emoji: "⛔", keywords: "no entry" },
    { emoji: "🚫", keywords: "prohibited" },
    { emoji: "🚳", keywords: "no bicycles" },
    { emoji: "🚭", keywords: "no smoking" },
    { emoji: "🚯", keywords: "no littering" },
    { emoji: "🚱", keywords: "non potable water" },
    { emoji: "🚷", keywords: "no pedestrians" },
    { emoji: "📵", keywords: "no mobile phones" },
    { emoji: "🔞", keywords: "no one under eighteen" },
    { emoji: "☢️", keywords: "radioactive" },
    { emoji: "☣️", keywords: "biohazard" },
    { emoji: "⬆️", keywords: "up arrow" },
    { emoji: "↗️", keywords: "up right arrow" },
    { emoji: "➡️", keywords: "right arrow" },
    { emoji: "↘️", keywords: "down right arrow" },
    { emoji: "⬇️", keywords: "down arrow" },
    { emoji: "↙️", keywords: "down left arrow" },
    { emoji: "⬅️", keywords: "left arrow" },
    { emoji: "↖️", keywords: "up left arrow" },
    { emoji: "↕️", keywords: "up down arrow" },
    { emoji: "↔️", keywords: "left right arrow" },
    { emoji: "↩️", keywords: "right arrow curving left" },
    { emoji: "↪️", keywords: "left arrow curving right" },
    { emoji: "⤴️", keywords: "right arrow curving up" },
    { emoji: "⤵️", keywords: "right arrow curving down" },
    { emoji: "🔃", keywords: "clockwise vertical arrows" },
    { emoji: "🔄", keywords: "counterclockwise arrows button" },
    { emoji: "🔙", keywords: "back arrow" },
    { emoji: "🔚", keywords: "end arrow" },
    { emoji: "🔛", keywords: "on arrow" },
    { emoji: "🔜", keywords: "soon arrow" },
    { emoji: "🔝", keywords: "top arrow" },
    { emoji: "🛐", keywords: "place of worship" },
    { emoji: "⚛️", keywords: "atom symbol" },
    { emoji: "🕉️", keywords: "om" },
    { emoji: "✡️", keywords: "star of david" },
    { emoji: "☸️", keywords: "wheel of dharma" },
    { emoji: "☯️", keywords: "yin yang" },
    { emoji: "✝️", keywords: "latin cross" },
    { emoji: "☦️", keywords: "orthodox cross" },
    { emoji: "☪️", keywords: "star and crescent" },
    { emoji: "☮️", keywords: "peace symbol" },
    { emoji: "🕎", keywords: "menorah" },
    { emoji: "🔯", keywords: "dotted six pointed star" },
    { emoji: "🪯", keywords: "khanda" },
    { emoji: "♈", keywords: "aries" },
    { emoji: "♉", keywords: "taurus" },
    { emoji: "♊", keywords: "gemini" },
    { emoji: "♋", keywords: "cancer" },
    { emoji: "♌", keywords: "leo" },
    { emoji: "♍", keywords: "virgo" },
    { emoji: "♎", keywords: "libra" },
    { emoji: "♏", keywords: "scorpio" },
    { emoji: "♐", keywords: "sagittarius" },
    { emoji: "♑", keywords: "capricorn" },
    { emoji: "♒", keywords: "aquarius" },
    { emoji: "♓", keywords: "pisces" },
    { emoji: "⛎", keywords: "ophiuchus" },
    { emoji: "🔀", keywords: "shuffle tracks button" },
    { emoji: "🔁", keywords: "repeat button" },
    { emoji: "🔂", keywords: "repeat single button" },
    { emoji: "▶️", keywords: "play button" },
    { emoji: "⏩", keywords: "fast forward button" },
    { emoji: "⏭️", keywords: "next track button" },
    { emoji: "⏯️", keywords: "play or pause button" },
    { emoji: "◀️", keywords: "reverse button" },
    { emoji: "⏪", keywords: "fast reverse button" },
    { emoji: "⏮️", keywords: "last track button" },
    { emoji: "🔼", keywords: "upwards button" },
    { emoji: "⏫", keywords: "fast up button" },
    { emoji: "🔽", keywords: "downwards button" },
    { emoji: "⏬", keywords: "fast down button" },
    { emoji: "⏸️", keywords: "pause button" },
    { emoji: "⏹️", keywords: "stop button" },
    { emoji: "⏺️", keywords: "record button" },
    { emoji: "⏏️", keywords: "eject button" },
    { emoji: "🎦", keywords: "cinema" },
    { emoji: "🔅", keywords: "dim button" },
    { emoji: "🔆", keywords: "bright button" },
    { emoji: "📶", keywords: "antenna bars" },
    { emoji: "🛜", keywords: "wireless" },
    { emoji: "📳", keywords: "vibration mode" },
    { emoji: "📴", keywords: "mobile phone off" },
    { emoji: "♀️", keywords: "female sign" },
    { emoji: "♂️", keywords: "male sign" },
    { emoji: "⚧️", keywords: "transgender symbol" },
    { emoji: "✖️", keywords: "multiply" },
    { emoji: "➕", keywords: "plus" },
    { emoji: "➖", keywords: "minus" },
    { emoji: "➗", keywords: "divide" },
    { emoji: "🟰", keywords: "heavy equals sign" },
    { emoji: "♾️", keywords: "infinity" },
    { emoji: "‼️", keywords: "double exclamation mark" },
    { emoji: "⁉️", keywords: "exclamation question mark" },
    { emoji: "❓", keywords: "red question mark" },
    { emoji: "❔", keywords: "white question mark" },
    { emoji: "❕", keywords: "white exclamation mark" },
    { emoji: "❗", keywords: "red exclamation mark" },
    { emoji: "〰️", keywords: "wavy dash" },
    { emoji: "💱", keywords: "currency exchange" },
    { emoji: "💲", keywords: "heavy dollar sign" },
    { emoji: "⚕️", keywords: "medical symbol" },
    { emoji: "♻️", keywords: "recycling symbol" },
    { emoji: "⚜️", keywords: "fleur de lis" },
    { emoji: "🔱", keywords: "trident emblem" },
    { emoji: "📛", keywords: "name badge" },
    { emoji: "🔰", keywords: "japanese symbol for beginner" },
    { emoji: "⭕", keywords: "hollow red circle" },
    { emoji: "✅", keywords: "check mark button" },
    { emoji: "☑️", keywords: "check box with" },
    { emoji: "✔️", keywords: "check mark" },
    { emoji: "❌", keywords: "cross mark" },
    { emoji: "❎", keywords: "cross mark button" },
    { emoji: "➰", keywords: "curly loop" },
    { emoji: "➿", keywords: "double curly loop" },
    { emoji: "〽️", keywords: "part alternation mark" },
    { emoji: "✳️", keywords: "eight spoked asterisk" },
    { emoji: "✴️", keywords: "eight pointed star" },
    { emoji: "❇️", keywords: "sparkle" },
    { emoji: "©️", keywords: "copyright" },
    { emoji: "®️", keywords: "registered" },
    { emoji: "™️", keywords: "trade mark" },
    { emoji: "🫟", keywords: "splatter" },
    { emoji: "#️⃣", keywords: "keycap number sign" },
    { emoji: "*️⃣", keywords: "keycap asterisk" },
    { emoji: "0️⃣", keywords: "keycap 0" },
    { emoji: "1️⃣", keywords: "keycap 1" },
    { emoji: "2️⃣", keywords: "keycap 2" },
    { emoji: "3️⃣", keywords: "keycap 3" },
    { emoji: "4️⃣", keywords: "keycap 4" },
    { emoji: "5️⃣", keywords: "keycap 5" },
    { emoji: "6️⃣", keywords: "keycap 6" },
    { emoji: "7️⃣", keywords: "keycap 7" },
    { emoji: "8️⃣", keywords: "keycap 8" },
    { emoji: "9️⃣", keywords: "keycap 9" },
    { emoji: "🔟", keywords: "keycap 10" },
    { emoji: "🔠", keywords: "input latin uppercase" },
    { emoji: "🔡", keywords: "input latin lowercase" },
    { emoji: "🔢", keywords: "input numbers" },
    { emoji: "🔣", keywords: "input symbols" },
    { emoji: "🔤", keywords: "input latin letters" },
    { emoji: "🅰️", keywords: "a button blood type" },
    { emoji: "🆎", keywords: "ab button blood type" },
    { emoji: "🅱️", keywords: "b button blood type" },
    { emoji: "🆑", keywords: "cl button" },
    { emoji: "🆒", keywords: "cool button" },
    { emoji: "🆓", keywords: "free button" },
    { emoji: "ℹ️", keywords: "information" },
    { emoji: "🆔", keywords: "id button" },
    { emoji: "Ⓜ️", keywords: "circled m" },
    { emoji: "🆕", keywords: "new button" },
    { emoji: "🆖", keywords: "ng button" },
    { emoji: "🅾️", keywords: "o button blood type" },
    { emoji: "🆗", keywords: "ok button" },
    { emoji: "🅿️", keywords: "p button" },
    { emoji: "🆘", keywords: "sos button" },
    { emoji: "🆙", keywords: "up button" },
    { emoji: "🆚", keywords: "vs button" },
    { emoji: "🈁", keywords: "japanese here button" },
    { emoji: "🈂️", keywords: "japanese service charge button" },
    { emoji: "🈷️", keywords: "japanese monthly amount button" },
    { emoji: "🈶", keywords: "japanese not free of charge button" },
    { emoji: "🈯", keywords: "japanese reserved button" },
    { emoji: "🉐", keywords: "japanese bargain button" },
    { emoji: "🈹", keywords: "japanese discount button" },
    { emoji: "🈚", keywords: "japanese free of charge button" },
    { emoji: "🈲", keywords: "japanese prohibited button" },
    { emoji: "🉑", keywords: "japanese acceptable button" },
    { emoji: "🈸", keywords: "japanese application button" },
    { emoji: "🈴", keywords: "japanese passing grade button" },
    { emoji: "🈳", keywords: "japanese vacancy button" },
    { emoji: "㊗️", keywords: "japanese congratulations button" },
    { emoji: "㊙️", keywords: "japanese secret button" },
    { emoji: "🈺", keywords: "japanese open for business button" },
    { emoji: "🈵", keywords: "japanese no vacancy button" },
    { emoji: "🔴", keywords: "red circle" },
    { emoji: "🟠", keywords: "orange circle" },
    { emoji: "🟡", keywords: "yellow circle" },
    { emoji: "🟢", keywords: "green circle" },
    { emoji: "🔵", keywords: "blue circle" },
    { emoji: "🟣", keywords: "purple circle" },
    { emoji: "🟤", keywords: "brown circle" },
    { emoji: "⚫", keywords: "black circle" },
    { emoji: "⚪", keywords: "white circle" },
    { emoji: "🟥", keywords: "red square" },
    { emoji: "🟧", keywords: "orange square" },
    { emoji: "🟨", keywords: "yellow square" },
    { emoji: "🟩", keywords: "green square" },
    { emoji: "🟦", keywords: "blue square" },
    { emoji: "🟪", keywords: "purple square" },
    { emoji: "🟫", keywords: "brown square" },
    { emoji: "⬛", keywords: "black large square" },
    { emoji: "⬜", keywords: "white large square" },
    { emoji: "◼️", keywords: "black medium square" },
    { emoji: "◻️", keywords: "white medium square" },
    { emoji: "◾", keywords: "black medium small square" },
    { emoji: "◽", keywords: "white medium small square" },
    { emoji: "▪️", keywords: "black small square" },
    { emoji: "▫️", keywords: "white small square" },
    { emoji: "🔶", keywords: "large orange diamond" },
    { emoji: "🔷", keywords: "large blue diamond" },
    { emoji: "🔸", keywords: "small orange diamond" },
    { emoji: "🔹", keywords: "small blue diamond" },
    { emoji: "🔺", keywords: "red triangle pointed up" },
    { emoji: "🔻", keywords: "red triangle pointed down" },
    { emoji: "💠", keywords: "diamond with a dot" },
    { emoji: "🔘", keywords: "radio button" },
    { emoji: "🔳", keywords: "white square button" },
    { emoji: "🔲", keywords: "black square button" },
    ],
  },
  {
    name: "Flags",
    emojis: [
    { emoji: "🏁", keywords: "chequered flag" },
    { emoji: "🚩", keywords: "triangular flag" },
    { emoji: "🎌", keywords: "crossed flags" },
    { emoji: "🏴", keywords: "black flag" },
    { emoji: "🏳️", keywords: "white flag" },
    { emoji: "🏳️‍🌈", keywords: "rainbow flag" },
    { emoji: "🏳️‍⚧️", keywords: "transgender flag" },
    { emoji: "🏴‍☠️", keywords: "pirate flag" },
    { emoji: "🇦🇨", keywords: "flag ascension island" },
    { emoji: "🇦🇩", keywords: "flag andorra" },
    { emoji: "🇦🇪", keywords: "flag united arab emirates" },
    { emoji: "🇦🇫", keywords: "flag afghanistan" },
    { emoji: "🇦🇬", keywords: "flag antigua barbuda" },
    { emoji: "🇦🇮", keywords: "flag anguilla" },
    { emoji: "🇦🇱", keywords: "flag albania" },
    { emoji: "🇦🇲", keywords: "flag armenia" },
    { emoji: "🇦🇴", keywords: "flag angola" },
    { emoji: "🇦🇶", keywords: "flag antarctica" },
    { emoji: "🇦🇷", keywords: "flag argentina" },
    { emoji: "🇦🇸", keywords: "flag american samoa" },
    { emoji: "🇦🇹", keywords: "flag austria" },
    { emoji: "🇦🇺", keywords: "flag australia" },
    { emoji: "🇦🇼", keywords: "flag aruba" },
    { emoji: "🇦🇽", keywords: "flag land islands aland" },
    { emoji: "🇦🇿", keywords: "flag azerbaijan" },
    { emoji: "🇧🇦", keywords: "flag bosnia herzegovina" },
    { emoji: "🇧🇧", keywords: "flag barbados" },
    { emoji: "🇧🇩", keywords: "flag bangladesh" },
    { emoji: "🇧🇪", keywords: "flag belgium" },
    { emoji: "🇧🇫", keywords: "flag burkina faso" },
    { emoji: "🇧🇬", keywords: "flag bulgaria" },
    { emoji: "🇧🇭", keywords: "flag bahrain" },
    { emoji: "🇧🇮", keywords: "flag burundi" },
    { emoji: "🇧🇯", keywords: "flag benin" },
    { emoji: "🇧🇱", keywords: "flag st barth lemy barthelemy" },
    { emoji: "🇧🇲", keywords: "flag bermuda" },
    { emoji: "🇧🇳", keywords: "flag brunei" },
    { emoji: "🇧🇴", keywords: "flag bolivia" },
    { emoji: "🇧🇶", keywords: "flag caribbean netherlands" },
    { emoji: "🇧🇷", keywords: "flag brazil" },
    { emoji: "🇧🇸", keywords: "flag bahamas" },
    { emoji: "🇧🇹", keywords: "flag bhutan" },
    { emoji: "🇧🇻", keywords: "flag bouvet island" },
    { emoji: "🇧🇼", keywords: "flag botswana" },
    { emoji: "🇧🇾", keywords: "flag belarus" },
    { emoji: "🇧🇿", keywords: "flag belize" },
    { emoji: "🇨🇦", keywords: "flag canada" },
    { emoji: "🇨🇨", keywords: "flag cocos keeling islands" },
    { emoji: "🇨🇩", keywords: "flag congo kinshasa" },
    { emoji: "🇨🇫", keywords: "flag central african republic" },
    { emoji: "🇨🇬", keywords: "flag congo brazzaville" },
    { emoji: "🇨🇭", keywords: "flag switzerland" },
    { emoji: "🇨🇮", keywords: "flag c te d ivoire cote" },
    { emoji: "🇨🇰", keywords: "flag cook islands" },
    { emoji: "🇨🇱", keywords: "flag chile" },
    { emoji: "🇨🇲", keywords: "flag cameroon" },
    { emoji: "🇨🇳", keywords: "flag china" },
    { emoji: "🇨🇴", keywords: "flag colombia" },
    { emoji: "🇨🇵", keywords: "flag clipperton island" },
    { emoji: "🇨🇶", keywords: "flag sark" },
    { emoji: "🇨🇷", keywords: "flag costa rica" },
    { emoji: "🇨🇺", keywords: "flag cuba" },
    { emoji: "🇨🇻", keywords: "flag cape verde" },
    { emoji: "🇨🇼", keywords: "flag cura ao curacao" },
    { emoji: "🇨🇽", keywords: "flag christmas island" },
    { emoji: "🇨🇾", keywords: "flag cyprus" },
    { emoji: "🇨🇿", keywords: "flag czechia" },
    { emoji: "🇩🇪", keywords: "flag germany" },
    { emoji: "🇩🇬", keywords: "flag diego garcia" },
    { emoji: "🇩🇯", keywords: "flag djibouti" },
    { emoji: "🇩🇰", keywords: "flag denmark" },
    { emoji: "🇩🇲", keywords: "flag dominica" },
    { emoji: "🇩🇴", keywords: "flag dominican republic" },
    { emoji: "🇩🇿", keywords: "flag algeria" },
    { emoji: "🇪🇦", keywords: "flag ceuta melilla" },
    { emoji: "🇪🇨", keywords: "flag ecuador" },
    { emoji: "🇪🇪", keywords: "flag estonia" },
    { emoji: "🇪🇬", keywords: "flag egypt" },
    { emoji: "🇪🇭", keywords: "flag western sahara" },
    { emoji: "🇪🇷", keywords: "flag eritrea" },
    { emoji: "🇪🇸", keywords: "flag spain" },
    { emoji: "🇪🇹", keywords: "flag ethiopia" },
    { emoji: "🇪🇺", keywords: "flag european union" },
    { emoji: "🇫🇮", keywords: "flag finland" },
    { emoji: "🇫🇯", keywords: "flag fiji" },
    { emoji: "🇫🇰", keywords: "flag falkland islands" },
    { emoji: "🇫🇲", keywords: "flag micronesia" },
    { emoji: "🇫🇴", keywords: "flag faroe islands" },
    { emoji: "🇫🇷", keywords: "flag france" },
    { emoji: "🇬🇦", keywords: "flag gabon" },
    { emoji: "🇬🇧", keywords: "flag united kingdom" },
    { emoji: "🇬🇩", keywords: "flag grenada" },
    { emoji: "🇬🇪", keywords: "flag georgia" },
    { emoji: "🇬🇫", keywords: "flag french guiana" },
    { emoji: "🇬🇬", keywords: "flag guernsey" },
    { emoji: "🇬🇭", keywords: "flag ghana" },
    { emoji: "🇬🇮", keywords: "flag gibraltar" },
    { emoji: "🇬🇱", keywords: "flag greenland" },
    { emoji: "🇬🇲", keywords: "flag gambia" },
    { emoji: "🇬🇳", keywords: "flag guinea" },
    { emoji: "🇬🇵", keywords: "flag guadeloupe" },
    { emoji: "🇬🇶", keywords: "flag equatorial guinea" },
    { emoji: "🇬🇷", keywords: "flag greece" },
    { emoji: "🇬🇸", keywords: "flag south georgia sandwich islands" },
    { emoji: "🇬🇹", keywords: "flag guatemala" },
    { emoji: "🇬🇺", keywords: "flag guam" },
    { emoji: "🇬🇼", keywords: "flag guinea bissau" },
    { emoji: "🇬🇾", keywords: "flag guyana" },
    { emoji: "🇭🇰", keywords: "flag hong kong sar china" },
    { emoji: "🇭🇲", keywords: "flag heard mcdonald islands" },
    { emoji: "🇭🇳", keywords: "flag honduras" },
    { emoji: "🇭🇷", keywords: "flag croatia" },
    { emoji: "🇭🇹", keywords: "flag haiti" },
    { emoji: "🇭🇺", keywords: "flag hungary" },
    { emoji: "🇮🇨", keywords: "flag canary islands" },
    { emoji: "🇮🇩", keywords: "flag indonesia" },
    { emoji: "🇮🇪", keywords: "flag ireland" },
    { emoji: "🇮🇱", keywords: "flag israel" },
    { emoji: "🇮🇲", keywords: "flag isle of man" },
    { emoji: "🇮🇳", keywords: "flag india" },
    { emoji: "🇮🇴", keywords: "flag british indian ocean territory" },
    { emoji: "🇮🇶", keywords: "flag iraq" },
    { emoji: "🇮🇷", keywords: "flag iran" },
    { emoji: "🇮🇸", keywords: "flag iceland" },
    { emoji: "🇮🇹", keywords: "flag italy" },
    { emoji: "🇯🇪", keywords: "flag jersey" },
    { emoji: "🇯🇲", keywords: "flag jamaica" },
    { emoji: "🇯🇴", keywords: "flag jordan" },
    { emoji: "🇯🇵", keywords: "flag japan" },
    { emoji: "🇰🇪", keywords: "flag kenya" },
    { emoji: "🇰🇬", keywords: "flag kyrgyzstan" },
    { emoji: "🇰🇭", keywords: "flag cambodia" },
    { emoji: "🇰🇮", keywords: "flag kiribati" },
    { emoji: "🇰🇲", keywords: "flag comoros" },
    { emoji: "🇰🇳", keywords: "flag st kitts nevis" },
    { emoji: "🇰🇵", keywords: "flag north korea" },
    { emoji: "🇰🇷", keywords: "flag south korea" },
    { emoji: "🇰🇼", keywords: "flag kuwait" },
    { emoji: "🇰🇾", keywords: "flag cayman islands" },
    { emoji: "🇰🇿", keywords: "flag kazakhstan" },
    { emoji: "🇱🇦", keywords: "flag laos" },
    { emoji: "🇱🇧", keywords: "flag lebanon" },
    { emoji: "🇱🇨", keywords: "flag st lucia" },
    { emoji: "🇱🇮", keywords: "flag liechtenstein" },
    { emoji: "🇱🇰", keywords: "flag sri lanka" },
    { emoji: "🇱🇷", keywords: "flag liberia" },
    { emoji: "🇱🇸", keywords: "flag lesotho" },
    { emoji: "🇱🇹", keywords: "flag lithuania" },
    { emoji: "🇱🇺", keywords: "flag luxembourg" },
    { emoji: "🇱🇻", keywords: "flag latvia" },
    { emoji: "🇱🇾", keywords: "flag libya" },
    { emoji: "🇲🇦", keywords: "flag morocco" },
    { emoji: "🇲🇨", keywords: "flag monaco" },
    { emoji: "🇲🇩", keywords: "flag moldova" },
    { emoji: "🇲🇪", keywords: "flag montenegro" },
    { emoji: "🇲🇫", keywords: "flag st martin" },
    { emoji: "🇲🇬", keywords: "flag madagascar" },
    { emoji: "🇲🇭", keywords: "flag marshall islands" },
    { emoji: "🇲🇰", keywords: "flag north macedonia" },
    { emoji: "🇲🇱", keywords: "flag mali" },
    { emoji: "🇲🇲", keywords: "flag myanmar burma" },
    { emoji: "🇲🇳", keywords: "flag mongolia" },
    { emoji: "🇲🇴", keywords: "flag macao sar china" },
    { emoji: "🇲🇵", keywords: "flag northern mariana islands" },
    { emoji: "🇲🇶", keywords: "flag martinique" },
    { emoji: "🇲🇷", keywords: "flag mauritania" },
    { emoji: "🇲🇸", keywords: "flag montserrat" },
    { emoji: "🇲🇹", keywords: "flag malta" },
    { emoji: "🇲🇺", keywords: "flag mauritius" },
    { emoji: "🇲🇻", keywords: "flag maldives" },
    { emoji: "🇲🇼", keywords: "flag malawi" },
    { emoji: "🇲🇽", keywords: "flag mexico" },
    { emoji: "🇲🇾", keywords: "flag malaysia" },
    { emoji: "🇲🇿", keywords: "flag mozambique" },
    { emoji: "🇳🇦", keywords: "flag namibia" },
    { emoji: "🇳🇨", keywords: "flag new caledonia" },
    { emoji: "🇳🇪", keywords: "flag niger" },
    { emoji: "🇳🇫", keywords: "flag norfolk island" },
    { emoji: "🇳🇬", keywords: "flag nigeria" },
    { emoji: "🇳🇮", keywords: "flag nicaragua" },
    { emoji: "🇳🇱", keywords: "flag netherlands" },
    { emoji: "🇳🇴", keywords: "flag norway" },
    { emoji: "🇳🇵", keywords: "flag nepal" },
    { emoji: "🇳🇷", keywords: "flag nauru" },
    { emoji: "🇳🇺", keywords: "flag niue" },
    { emoji: "🇳🇿", keywords: "flag new zealand" },
    { emoji: "🇴🇲", keywords: "flag oman" },
    { emoji: "🇵🇦", keywords: "flag panama" },
    { emoji: "🇵🇪", keywords: "flag peru" },
    { emoji: "🇵🇫", keywords: "flag french polynesia" },
    { emoji: "🇵🇬", keywords: "flag papua new guinea" },
    { emoji: "🇵🇭", keywords: "flag philippines" },
    { emoji: "🇵🇰", keywords: "flag pakistan" },
    { emoji: "🇵🇱", keywords: "flag poland" },
    { emoji: "🇵🇲", keywords: "flag st pierre miquelon" },
    { emoji: "🇵🇳", keywords: "flag pitcairn islands" },
    { emoji: "🇵🇷", keywords: "flag puerto rico" },
    { emoji: "🇵🇸", keywords: "flag palestinian territories" },
    { emoji: "🇵🇹", keywords: "flag portugal" },
    { emoji: "🇵🇼", keywords: "flag palau" },
    { emoji: "🇵🇾", keywords: "flag paraguay" },
    { emoji: "🇶🇦", keywords: "flag qatar" },
    { emoji: "🇷🇪", keywords: "flag r union reunion" },
    { emoji: "🇷🇴", keywords: "flag romania" },
    { emoji: "🇷🇸", keywords: "flag serbia" },
    { emoji: "🇷🇺", keywords: "flag russia" },
    { emoji: "🇷🇼", keywords: "flag rwanda" },
    { emoji: "🇸🇦", keywords: "flag saudi arabia" },
    { emoji: "🇸🇧", keywords: "flag solomon islands" },
    { emoji: "🇸🇨", keywords: "flag seychelles" },
    { emoji: "🇸🇩", keywords: "flag sudan" },
    { emoji: "🇸🇪", keywords: "flag sweden" },
    { emoji: "🇸🇬", keywords: "flag singapore" },
    { emoji: "🇸🇭", keywords: "flag st helena" },
    { emoji: "🇸🇮", keywords: "flag slovenia" },
    { emoji: "🇸🇯", keywords: "flag svalbard jan mayen" },
    { emoji: "🇸🇰", keywords: "flag slovakia" },
    { emoji: "🇸🇱", keywords: "flag sierra leone" },
    { emoji: "🇸🇲", keywords: "flag san marino" },
    { emoji: "🇸🇳", keywords: "flag senegal" },
    { emoji: "🇸🇴", keywords: "flag somalia" },
    { emoji: "🇸🇷", keywords: "flag suriname" },
    { emoji: "🇸🇸", keywords: "flag south sudan" },
    { emoji: "🇸🇹", keywords: "flag s o tom pr ncipe sao tome principe" },
    { emoji: "🇸🇻", keywords: "flag el salvador" },
    { emoji: "🇸🇽", keywords: "flag sint maarten" },
    { emoji: "🇸🇾", keywords: "flag syria" },
    { emoji: "🇸🇿", keywords: "flag eswatini" },
    { emoji: "🇹🇦", keywords: "flag tristan da cunha" },
    { emoji: "🇹🇨", keywords: "flag turks caicos islands" },
    { emoji: "🇹🇩", keywords: "flag chad" },
    { emoji: "🇹🇫", keywords: "flag french southern territories" },
    { emoji: "🇹🇬", keywords: "flag togo" },
    { emoji: "🇹🇭", keywords: "flag thailand" },
    { emoji: "🇹🇯", keywords: "flag tajikistan" },
    { emoji: "🇹🇰", keywords: "flag tokelau" },
    { emoji: "🇹🇱", keywords: "flag timor leste" },
    { emoji: "🇹🇲", keywords: "flag turkmenistan" },
    { emoji: "🇹🇳", keywords: "flag tunisia" },
    { emoji: "🇹🇴", keywords: "flag tonga" },
    { emoji: "🇹🇷", keywords: "flag t rkiye turkiye" },
    { emoji: "🇹🇹", keywords: "flag trinidad tobago" },
    { emoji: "🇹🇻", keywords: "flag tuvalu" },
    { emoji: "🇹🇼", keywords: "flag taiwan" },
    { emoji: "🇹🇿", keywords: "flag tanzania" },
    { emoji: "🇺🇦", keywords: "flag ukraine" },
    { emoji: "🇺🇬", keywords: "flag uganda" },
    { emoji: "🇺🇲", keywords: "flag u s outlying islands" },
    { emoji: "🇺🇳", keywords: "flag united nations" },
    { emoji: "🇺🇸", keywords: "flag united states" },
    { emoji: "🇺🇾", keywords: "flag uruguay" },
    { emoji: "🇺🇿", keywords: "flag uzbekistan" },
    { emoji: "🇻🇦", keywords: "flag vatican city" },
    { emoji: "🇻🇨", keywords: "flag st vincent grenadines" },
    { emoji: "🇻🇪", keywords: "flag venezuela" },
    { emoji: "🇻🇬", keywords: "flag british virgin islands" },
    { emoji: "🇻🇮", keywords: "flag u s virgin islands" },
    { emoji: "🇻🇳", keywords: "flag vietnam" },
    { emoji: "🇻🇺", keywords: "flag vanuatu" },
    { emoji: "🇼🇫", keywords: "flag wallis futuna" },
    { emoji: "🇼🇸", keywords: "flag samoa" },
    { emoji: "🇽🇰", keywords: "flag kosovo" },
    { emoji: "🇾🇪", keywords: "flag yemen" },
    { emoji: "🇾🇹", keywords: "flag mayotte" },
    { emoji: "🇿🇦", keywords: "flag south africa" },
    { emoji: "🇿🇲", keywords: "flag zambia" },
    { emoji: "🇿🇼", keywords: "flag zimbabwe" },
    { emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", keywords: "flag england" },
    { emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", keywords: "flag scotland" },
    { emoji: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", keywords: "flag wales" },
    ],
  },
];
