#!/usr/bin/env python3
"""Generate the three README images, in a light and a dark variant each.

    python3 scripts/gen-readme-assets.py

Writes six files into docs/assets/. Never hand-edit those — a re-run silently
overwrites them. Change this script instead.

Why a generator and not six checked-in files: each asset exists twice, once per
theme, and the two differ ONLY in the palette. Hand-maintaining that pair is the
same drift trap CLAUDE.md records for the provider count — the second copy stops
matching the first and nothing fails. Here the pair is one source and one loop.

Three constraints come from GitHub rendering a README image as a bare <img>,
in isolation, with no document around it:

  * No external anything. No <style>, no class=, no webfont, no href to another
    file. Everything is a presentation attribute on the element itself.
  * <text> renders in the VIEWER's fonts, so metrics vary by platform. Every
    string here is short and every box has slack; nothing is measured-to-fit.
  * `prefers-color-scheme` cannot reach inside the image, so the theme swap
    happens OUTSIDE it, via <picture> in the README. Hence two files.

Brand marks are read from web/ui/src/assets/logos/ (the vendored set, itself
generated by scripts/vendor-brand-logos.sh) rather than copied here, so a
re-vendor reaches these images too.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOGO_DIR = ROOT / "web" / "ui" / "src" / "assets" / "logos"
OUT_DIR = ROOT / "docs" / "assets"


def provider_count() -> int:
    return len(list((ROOT / "internal" / "connectors" / "providers").glob("*.yaml")))


def provider_approx() -> str:
    """The provider count rounded DOWN to a hundred, as "100+".

    An exact count goes stale between releases — connector waves land often
    enough that the number on a picture is wrong more days than it is right.
    Rounding down keeps it true by construction and still auto-advances: at 210
    providers this says "200+" without anyone editing a file.

    Down, never nearest, is the whole point — "100+" against a real 136 is
    honest, "200+" against it is a lie, and scripts/check-docs-sync.py's
    check_inflated fails the build on exactly that direction. Below 100 there
    is no honest round number left, so it degrades to the exact count rather
    than claiming "0+".
    """
    n = provider_count()
    floor = n // 100 * 100
    return f"{floor}+" if floor >= 100 else str(n)


def skill_count() -> int:
    return sum(
        1 for p in (ROOT / "internal" / "skilllibrary" / "skills").iterdir() if p.is_dir()
    )

# The one font stack. SVG text falls back through it on the viewer's machine;
# there is no webfont to load, so this is a best-effort match, not a guarantee.
FONT = (
    "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', "
    "Roboto, Helvetica, Arial, sans-serif"
)


class Palette:
    """Colour tokens for one theme.

    Light mirrors rookery-web's src/styles/brand.css exactly. Dark is derived
    from the same file's Starlight dark block (accent #e08d51, black #17140f),
    so the two repositories stay recognisably one brand.
    """

    def __init__(self, **kw: str) -> None:
        self.__dict__.update(kw)


LIGHT = Palette(
    ground="#ece5db",   # --bone
    surface="#f8f4ee",  # --paper
    raised="#ece5db",
    ink="#211d1a",      # --bark
    muted="#6f6760",    # --stone
    ember="#a94c1c",    # --ember
    ember_soft="#f6e6dc",
    line="#d9cfc2",     # --line
    dusk="#46405a",     # --dusk
    logo_tile="#ffffff",
)

DARK = Palette(
    ground="#17140f",
    surface="#1f1b16",
    raised="#26211a",
    ink="#ece5db",
    muted="#a0968a",
    ember="#e08d51",
    ember_soft="#2f2118",
    line="#3a332a",
    dusk="#b3a9c9",
    # Brand marks are drawn for a light ground and many are near-white; they
    # keep their own pale tile on dark rather than dissolving into it.
    logo_tile="#f4f0ea",
)


# --------------------------------------------------------------------------
# lucide icons
# --------------------------------------------------------------------------
# Path data lifted verbatim from lucide-static v1.30.0 (ISC).
#
# The eleven feature icons are exactly the ones rookery-web's landing page
# imports (src/pages/index.astro imports them from lucide-react directly — NOT
# via FeatureSection.tsx, whose own ICONS map covers only six of them). The
# twelfth, shield-check, is ours: Landlock has no card on the website.
#
# The website is on lucide-react 1.29.0 while this is lucide-static 1.30.0, a
# minor apart. Every one of these icons was compared child-shape by child-shape
# across the two packages and is identical, so "the same icons" is a measured
# claim rather than an assumed one — but it is worth re-measuring if either
# package is bumped. All are 24x24, stroked.

LUCIDE: dict[str, list[str]] = {
    "layers": [
        '<path d="M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z"/>',
        '<path d="M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12"/>',
        '<path d="M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17"/>',
    ],
    "book-text": [
        '<path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20"/>',
        '<path d="M8 11h8"/>',
        '<path d="M8 7h6"/>',
    ],
    "bot": [
        '<path d="M12 8V4H8"/>',
        '<rect width="16" height="12" x="4" y="8" rx="2"/>',
        '<path d="M2 14h2"/>',
        '<path d="M20 14h2"/>',
        '<path d="M15 13v2"/>',
        '<path d="M9 13v2"/>',
    ],
    "puzzle": [
        '<path d="M15.39 4.39a1 1 0 0 0 1.68-.474 2.5 2.5 0 1 1 3.014 3.015 1 1 0 0 0-.474 1.68l1.683 1.682a2.414 2.414 0 0 1 0 3.414L19.61 15.39a1 1 0 0 1-1.68-.474 2.5 2.5 0 1 0-3.014 3.015 1 1 0 0 1 .474 1.68l-1.683 1.682a2.414 2.414 0 0 1-3.414 0L8.61 19.61a1 1 0 0 0-1.68.474 2.5 2.5 0 1 1-3.014-3.015 1 1 0 0 0 .474-1.68l-1.683-1.682a2.414 2.414 0 0 1 0-3.414L4.39 8.61a1 1 0 0 1 1.68.474 2.5 2.5 0 1 0 3.014-3.015 1 1 0 0 1-.474-1.68l1.683-1.682a2.414 2.414 0 0 1 3.414 0z"/>',
    ],
    "plug": [
        '<path d="M12 22v-5"/>',
        '<path d="M15 8V2"/>',
        '<path d="M17 8a1 1 0 0 1 1 1v4a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1z"/>',
        '<path d="M9 8V2"/>',
    ],
    "terminal": [
        '<path d="M12 19h8"/>',
        '<path d="m4 17 6-6-6-6"/>',
    ],
    "messages-square": [
        '<path d="M16 10a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 14.286V4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>',
        '<path d="M20 9a2 2 0 0 1 2 2v10.286a.71.71 0 0 1-1.212.502l-2.202-2.202A2 2 0 0 0 17.172 19H10a2 2 0 0 1-2-2v-1"/>',
    ],
    "bell": [
        '<path d="M10.268 21a2 2 0 0 0 3.464 0"/>',
        '<path d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"/>',
    ],
    "cpu": [
        '<path d="M12 20v2"/>', '<path d="M12 2v2"/>',
        '<path d="M17 20v2"/>', '<path d="M17 2v2"/>',
        '<path d="M2 12h2"/>', '<path d="M2 17h2"/>', '<path d="M2 7h2"/>',
        '<path d="M20 12h2"/>', '<path d="M20 17h2"/>', '<path d="M20 7h2"/>',
        '<path d="M7 20v2"/>', '<path d="M7 2v2"/>',
        '<rect x="4" y="4" width="16" height="16" rx="2"/>',
        '<rect x="8" y="8" width="8" height="8" rx="1"/>',
    ],
    "key-round": [
        '<path d="M2.586 17.414A2 2 0 0 0 2 18.828V21a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h1a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h.172a2 2 0 0 0 1.414-.586l.814-.814a6.5 6.5 0 1 0-4-4z"/>',
        '<circle cx="16.5" cy="7.5" r=".5" fill="currentColor"/>',
    ],
    "calendar-clock": [
        '<path d="M16 14v2.2l1.6 1"/>',
        '<path d="M16 2v3"/>',
        '<path d="M21 7.338V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h2.338"/>',
        '<path d="M3 9h5.859"/>',
        '<path d="M8 2v3"/>',
        '<circle cx="16" cy="16" r="6"/>',
    ],
    "shield-check": [
        '<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/>',
        '<path d="m9 12 2 2 4-4"/>',
    ],
    "monitor": [
        '<rect width="20" height="14" x="2" y="3" rx="2"/>',
        '<line x1="8" x2="16" y1="21" y2="21"/>',
        '<line x1="12" x2="12" y1="17" y2="21"/>',
    ],
}


def icon(name: str, x: float, y: float, size: float, color: str,
         width: float = 1.9) -> str:
    """Draw a lucide icon with its top-left at (x, y), scaled to `size` px."""
    s = size / 24.0
    body = "".join(LUCIDE[name])
    return (
        f'<g transform="translate({r(x)} {r(y)}) scale({r(s, 4)})" '
        f'fill="none" stroke="{color}" color="{color}" stroke-width="{width / s:.3f}" '
        f'stroke-linecap="round" stroke-linejoin="round">{body}</g>'
    )


# --------------------------------------------------------------------------
# brand marks
# --------------------------------------------------------------------------

_VIEWBOX = re.compile(r'viewBox="([\d.\-\s]+)"')
_ROOT = re.compile(r"^\s*<svg\b([^>]*)>(.*)</svg>\s*$", re.S)
_ID = re.compile(r'\bid="([^"]+)"')


def _namespace_ids(body: str, prefix: str) -> str:
    """Rewrite every internal id and every reference to it.

    Vendored marks reuse trivial ids — dropbox.svg and jira.svg both define
    `a` and `b`. Inline two of those in one document and the second mark's
    url(#a) resolves to the FIRST mark's gradient, which renders as a plausible
    wrong colour rather than as an error. Prefixing per mark is what prevents it.
    """
    ids = set(_ID.findall(body))
    for i in sorted(ids, key=len, reverse=True):
        new = f"{prefix}-{i}"
        body = body.replace(f'id="{i}"', f'id="{new}"')
        body = body.replace(f"url(#{i})", f"url(#{new})")
        body = body.replace(f'href="#{i}"', f'href="#{new}"')
    return body


def logo(slug: str, cx: float, cy: float, size: float, ink: str,
         max_ar: float = 1.25) -> str:
    """Draw a vendored brand mark centred on (cx, cy), fitted into `size` px.

    `max_ar` rejects wordmarks. A mark is fitted by its LONGEST side, so a wide
    lockup like stripe.svg (512x214) lands at 40% of the intended height and
    reads as a smudge next to square marks — visible only once rendered, and
    easy to mistake for a bad logo rather than a bad fit. Chat pills pass a
    looser bound because the Discord mark is genuinely wide at 1.35.
    """
    src = (LOGO_DIR / f"{slug}.svg").read_text()
    m = _ROOT.match(src.strip())
    if not m:
        sys.exit(f"gen-readme-assets: {slug}.svg has no parseable <svg> root")
    attrs, body = m.group(1), m.group(2)

    vb = _VIEWBOX.search(attrs)
    if not vb:
        sys.exit(f"gen-readme-assets: {slug}.svg declares no viewBox")
    x0, y0, w, h = (float(v) for v in vb.group(1).split())

    ar = w / h
    if not (1 / max_ar) <= ar <= max_ar:
        sys.exit(
            f"gen-readme-assets: {slug}.svg is {w:g}x{h:g} (aspect {ar:.2f}), "
            f"outside the {1 / max_ar:.2f}-{max_ar:.2f} band — it is a wordmark, "
            "not a square mark, and would render far smaller than its neighbours. "
            "Pick a different provider."
        )

    if "<style" in body or "class=" in body:
        # vendor-brand-logos.sh inlines class styles and strips <style>; a mark
        # that still carries either would render at the SVG default fill (black)
        # here, since there is no stylesheet in an <img>-rendered document.
        sys.exit(f"gen-readme-assets: {slug}.svg still carries class/<style>")

    body = _namespace_ids(body, slug.replace("_", "-"))

    scale = size / max(w, h)
    tx = cx - (w * scale) / 2 - x0 * scale
    ty = cy - (h * scale) / 2 - y0 * scale

    # Carry the root's own paint attributes onto the wrapper: several marks set
    # fill/fill-rule there and would otherwise lose them with the root. `color`
    # is set because a currentColor mark (github.svg) resolves it against the
    # CSS color property, which defaults to black — invisible on the dark sheet.
    carried = " ".join(
        f'{k}="{v}"'
        for k, v in re.findall(r'\b(fill|fill-rule|clip-rule|stroke)="([^"]+)"', attrs)
    )
    return (
        f'<g transform="translate({r(tx)} {r(ty)}) scale({r(scale, 5)})" '
        f'color="{ink}" {carried}>{body}</g>'
    )


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

def r(v: float, places: int = 2) -> str:
    """Trim float noise so the committed files diff readably."""
    s = f"{v:.{places}f}".rstrip("0").rstrip(".")
    return s or "0"


def esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def text(s: str, x: float, y: float, size: float, fill: str, *,
         weight: int = 400, anchor: str = "start", spacing: float | None = None,
         opacity: float | None = None) -> str:
    extra = ""
    if weight != 400:
        extra += f' font-weight="{weight}"'
    if anchor != "start":
        extra += f' text-anchor="{anchor}"'
    if spacing is not None:
        extra += f' letter-spacing="{spacing}"'
    if opacity is not None:
        extra += f' opacity="{opacity}"'
    return (
        f'<text x="{r(x)}" y="{r(y)}" font-size="{r(size)}" '
        f'fill="{fill}"{extra}>{esc(s)}</text>'
    )


def document(w: float, h: float, title: str, body: str) -> str:
    tid = re.sub(r"[^a-z]+", "-", title.lower()).strip("-")[:32]
    # xmlns:xlink is declared even though nothing here writes it: some vendored
    # marks (jira.svg) carry `xlink:href` on their gradients, and the prefix was
    # bound on the root <svg> that inlining discards. Without the declaration the
    # document is not well-formed XML and every browser renders a broken image.
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'xmlns:xlink="http://www.w3.org/1999/xlink" '
        f'viewBox="0 0 {r(w)} {r(h)}" '
        f'width="{r(w)}" height="{r(h)}" role="img" aria-labelledby="{tid}">'
        f"<title id=\"{tid}\">{esc(title)}</title>"
        f'<g font-family="{FONT}">{body}</g>'
        "</svg>\n"
    )


# --------------------------------------------------------------------------
# 1. hero banner
# --------------------------------------------------------------------------

def hero(p: Palette) -> str:
    W, H = 1280, 300
    o = [f'<rect width="{W}" height="{H}" fill="{p.ground}"/>']
    o.append(f'<circle cx="1168" cy="16" r="278" fill="{p.ember}" opacity="0.10"/>')
    o.append(f'<circle cx="72" cy="300" r="196" fill="{p.dusk}" opacity="0.08"/>')

    # The Rookery mark, drawn at 2.6x from the same three strokes as
    # web/ui/src/components/brand/RookeryMark.tsx.
    o.append(
        f'<g transform="translate(92 62) scale(2.6)" fill="none" stroke="{p.ember}" '
        'stroke-width="3.1" stroke-linecap="round">'
        '<path d="M11 8.5h10"/><path d="M7.5 14h17"/>'
        '<path d="M4.5 19.5C4.5 26 9.5 29 16 29S27.5 26 27.5 19.5"/></g>'
    )
    o.append(text("rookery", 200, 136, 86, p.ink, weight=600, spacing=-4))
    o.append(text("Your knowledge grew hands.", 94, 218, 40, p.ink,
                  weight=600, spacing=-1))
    o.append(text("Self-hosted AI agents that run on your own machine, "
                  "around the clock.", 94, 258, 22, p.muted))
    o.append(f'<rect x="94" y="278" width="72" height="4" rx="2" fill="{p.ember}"/>')
    return document(W, H, "Rookery — your knowledge grew hands", "".join(o))


# --------------------------------------------------------------------------
# 2. feature grid
# --------------------------------------------------------------------------
# Twelve cards, three across. Body lines are held to ~32 characters: the column
# is 312px of usable width and SVG text renders in whatever font the viewer has,
# so a line measured to fit here would overflow on a wider-metric platform.

# Two cards state a COUNT, and a count in an image is invisible to every
# grep-based check the repo has — which is exactly how README's provider number
# drifted for months before scripts/check-docs-sync.py existed. So both are
# measured from source here rather than typed, and `--check` fails CI when the
# committed file no longer matches a fresh render. The provider count is
# additionally rounded down (see provider_approx) because connector waves land
# faster than the images get looked at.
def feature_cards() -> list[tuple[str, str, str]]:
    return [
        ("layers",          "Workspaces",     "Sealed, separate tenants."),
        ("book-text",       "Knowledge base", "Plain markdown on your disk."),
        ("bot",             "Agents",         "Describe it. It gets built."),
        ("puzzle",          "Skills",         f"{skill_count()} built in, ready to attach."),
        ("plug",            "Connections",    f"{provider_approx()} services. Your credentials."),
        ("terminal",        "MCP servers",    "Any server URL. Tools join in."),
        ("messages-square", "Chat",           "Ask what you know. Then act."),
        ("bell",            "Notifications",  "Inbox, Telegram, Discord, Slack."),
        ("cpu",             "Models",         "Your CLI, a provider, or local."),
        ("key-round",       "Secrets",        "Encrypted, scoped per workspace."),
        ("calendar-clock",  "Scheduling",     "Say when in plain words."),
        ("shield-check",    "Sandboxed",      "Landlock confines coders."),
    ]


def features(p: Palette) -> str:
    FEATURES = feature_cards()
    PAD, GAP, COLS = 40, 20, 3
    W = 1200
    cw = (W - 2 * PAD - (COLS - 1) * GAP) / COLS
    ch = 150
    rows = (len(FEATURES) + COLS - 1) // COLS
    H = PAD * 2 + rows * ch + (rows - 1) * GAP

    o = [f'<rect width="{W}" height="{r(H)}" fill="{p.ground}"/>']
    for i, (ic, title, body) in enumerate(FEATURES):
        x = PAD + (i % COLS) * (cw + GAP)
        y = PAD + (i // COLS) * (ch + GAP)
        o.append(
            f'<rect x="{r(x)}" y="{r(y)}" width="{r(cw)}" height="{ch}" rx="16" '
            f'fill="{p.surface}" stroke="{p.line}"/>'
        )
        o.append(
            f'<rect x="{r(x + 24)}" y="{r(y + 24)}" width="46" height="46" rx="13" '
            f'fill="{p.ember_soft}" stroke="{p.ember}" stroke-opacity="0.18"/>'
        )
        o.append(icon(ic, x + 35, y + 35, 24, p.ember))
        o.append(text(title, x + 24, y + 100, 23, p.ink, weight=600, spacing=-0.4))
        o.append(text(body, x + 24, y + 128, 15.5, p.muted))
    return document(W, H, "Rookery features: " + ", ".join(f[1] for f in FEATURES),
                    "".join(o))


# --------------------------------------------------------------------------
# 3. architecture
# --------------------------------------------------------------------------

CHAT = [("telegram", "Telegram"), ("discord", "Discord"), ("slack", "Slack")]

# A deliberate subset of the 136, chosen to span the range rather than to be
# complete: Google family, developer, docs, work tracking, commerce, money, AI,
# cloud, personal, self-hosted, media. All must be square marks — see `max_ar`.
WALL = [
    "google", "github", "notion", "jira", "shopify", "wise",
    "openai", "cloudflare", "todoist", "home_assistant", "immich", "spotify",
]


HEAD = 11  # arrowhead length


def arrow(x: float, y0: float, y1: float, color: str, both: bool = True) -> str:
    """A vertical arrow. Two-headed by default, because every edge here is.

    Chat is a conversation and notifications come back out over the same
    platforms; a connector is read AND write, and so is an MCP server. A
    single downward head drew the whole system as one-way, which is the one
    thing the picture must not say.
    """
    top = y0 + (HEAD if both else 0)
    parts = [
        f'<path d="M{r(x)} {r(top)}V{r(y1 - 9)}" stroke="{color}" stroke-width="2.5"/>',
        f'<path d="M{r(x - 7)} {r(y1 - HEAD)}l7 {HEAD} 7 -{HEAD}z" fill="{color}"/>',
    ]
    if both:
        parts.append(
            f'<path d="M{r(x - 7)} {r(y0 + HEAD)}l7 -{HEAD} 7 {HEAD}z" fill="{color}"/>'
        )
    return "".join(parts)


def architecture(p: Palette) -> str:
    W = 1200
    o: list[str] = []

    # -- you ---------------------------------------------------------------
    o.append(text("YOU", W / 2, 36, 13, p.muted, weight=600, spacing=2.4,
                  anchor="middle"))

    pill_w, pill_h, pill_gap = 176, 54, 22
    n = len(CHAT) + 1
    total = n * pill_w + (n - 1) * pill_gap
    px = (W - total) / 2
    py = 54
    for slug, label in CHAT:
        o.append(
            f'<rect x="{r(px)}" y="{py}" width="{pill_w}" height="{pill_h}" '
            f'rx="{pill_h / 2}" fill="{p.surface}" stroke="{p.line}"/>'
        )
        o.append(f'<circle cx="{r(px + 31)}" cy="{py + pill_h / 2}" r="15" '
                 f'fill="{p.logo_tile}"/>')
        o.append(logo(slug, px + 31, py + pill_h / 2, 21, p.ink, max_ar=1.4))
        o.append(text(label, px + 56, py + 34, 17, p.ink))
        px += pill_w + pill_gap
    o.append(
        f'<rect x="{r(px)}" y="{py}" width="{pill_w}" height="{pill_h}" '
        f'rx="{pill_h / 2}" fill="{p.surface}" stroke="{p.line}"/>'
    )
    o.append(icon("monitor", px + 20, py + 15, 24, p.ink, width=1.7))
    o.append(text("Browser", px + 56, py + 34, 17, p.ink))

    o.append(arrow(W / 2, py + pill_h + 6, 168, p.ember))

    # -- the binary --------------------------------------------------------
    bx, by, bw, bh = 70, 168, 1060, 352
    o.append(f'<rect x="{bx}" y="{by}" width="{bw}" height="{bh}" rx="24" '
             f'fill="{p.surface}" stroke="{p.line}" stroke-width="1.5"/>')
    o.append(text("YOUR MACHINE — ONE BINARY", bx + 30, by + 38, 14, p.ember,
                  weight=600, spacing=1.6))

    # Reading order follows how the thing is used: what you have, asking it,
    # sending it out, what it already knows how to do, what it authenticates
    # with. The coder is deliberately NOT among these — see the bar below.
    tiles = [("book-text", "Knowledge base"), ("messages-square", "Chat"),
             ("bot", "Agents"), ("puzzle", "Skills"), ("key-round", "Secrets")]
    tgap, tx0, tw_total = 20, bx + 30, bw - 60
    tw = (tw_total - (len(tiles) - 1) * tgap) / len(tiles)
    ty, th = by + 58, 186
    for i, (ic, label) in enumerate(tiles):
        x = tx0 + i * (tw + tgap)
        o.append(f'<rect x="{r(x)}" y="{ty}" width="{r(tw)}" height="{th}" rx="16" '
                 f'fill="{p.raised}" stroke="{p.line}"/>')
        cx = x + tw / 2
        o.append(f'<rect x="{r(cx - 29)}" y="{ty + 40}" width="58" height="58" rx="17" '
                 f'fill="{p.ember_soft}" stroke="{p.ember}" stroke-opacity="0.18"/>')
        o.append(icon(ic, cx - 15, ty + 55, 30, p.ember))
        o.append(text(label, cx, ty + 138, 19, p.ink, weight=600, anchor="middle"))

    # The coder is a SUBSTRATE, not a sibling. As one tile among five it read
    # as a feature you use alongside the others, when in fact every one of them
    # runs on it. One bar spanning the full width says that with geometry
    # instead of a caption, and its ember fill separates it from the tiles it
    # carries. Left-aligned icon + two lines mirrors the MCP box, so the
    # diagram has one way of drawing "thing, with a sentence about it".
    cy0, chh = ty + th + 18, 66
    o.append(f'<rect x="{tx0}" y="{r(cy0)}" width="{r(tw_total)}" height="{chh}" '
             f'rx="16" fill="{p.ember_soft}" stroke="{p.ember}" stroke-opacity="0.28"/>')
    o.append(icon("cpu", tx0 + 26, cy0 + 19, 28, p.ember))
    o.append(text("CODER", tx0 + 70, cy0 + 29, 16, p.ember, weight=600, spacing=1.6))
    o.append(text(
        "The model behind all of it — a CLI tool you already run, a hosted "
        "provider, or one on your own hardware.",
        tx0 + 70, cy0 + 52, 14.5, p.muted))

    # -- outward -----------------------------------------------------------
    oy, oh = 578, 132
    lw = 748
    rx0, rw = bx + lw + 22, W - (bx + lw + 22) - bx

    # One arrow per destination rather than a single stem landing between them:
    # the old layout drew nothing at all into MCP, which read as though only
    # connectors were reachable.
    o.append(arrow(bx + lw / 2, by + bh + 6, oy, p.ember))
    o.append(arrow(rx0 + rw / 2, by + bh + 6, oy, p.ember))

    o.append(f'<rect x="{bx}" y="{oy}" width="{lw}" height="{oh}" rx="20" '
             f'fill="{p.surface}" stroke="{p.line}"/>')
    o.append(text(f"{provider_approx()} CONNECTIONS", bx + 26, oy + 34, 13, p.muted,
                  weight=600, spacing=1.8))
    per_row = 6
    cell = (lw - 52) / per_row
    for i, slug in enumerate(WALL):
        cx = bx + 26 + cell * (i % per_row) + cell / 2
        cy = oy + 62 + (i // per_row) * 42
        o.append(f'<circle cx="{r(cx)}" cy="{r(cy)}" r="17" fill="{p.logo_tile}" '
                 f'stroke="{p.line}"/>')
        o.append(logo(slug, cx, cy, 21, "#211d1a"))

    o.append(f'<rect x="{r(rx0)}" y="{oy}" width="{r(rw)}" height="{oh}" rx="20" '
             f'fill="{p.surface}" stroke="{p.line}"/>')
    o.append(text("MCP SERVERS", rx0 + 26, oy + 34, 13, p.muted, weight=600,
                  spacing=1.8))
    o.append(f'<rect x="{r(rx0 + 26)}" y="{oy + 54}" width="52" height="52" rx="15" '
             f'fill="{p.ember_soft}" stroke="{p.ember}" stroke-opacity="0.18"/>')
    o.append(icon("terminal", rx0 + 39, oy + 67, 26, p.ember))
    o.append(text("Any server URL,", rx0 + 92, oy + 74, 16, p.ink))
    o.append(text("its own tool list.", rx0 + 92, oy + 96, 16, p.muted))

    H = oy + oh + 34
    return document(
        W, H,
        # provider_approx, not provider_count: this is what a screen reader is
        # told, so it must say the same thing the band says.
        "Rookery architecture: Telegram, Discord, Slack and a browser talk to one "
        "binary on your machine, holding the knowledge base, chat, agents, skills "
        "and secrets, all of them running on the coder — a CLI tool, a hosted "
        f"provider or a local model — and both reading and writing {provider_approx()} "
        "connections and any MCP server",
        "".join(o),
    )


# --------------------------------------------------------------------------

BUILDERS = {"hero-banner": hero, "features": features, "architecture": architecture}


def validate(path: Path, svg: str) -> None:
    """Refuse to write a file GitHub would render as a broken image.

    Both halves have already caught a real defect. A vendored mark carried
    `xlink:href` whose prefix was bound on the root element inlining discards,
    which is malformed XML — the browser shows the broken-image glyph, and
    nothing else in the toolchain would have said so.
    """
    import xml.etree.ElementTree as ET

    try:
        ET.fromstring(svg)
    except ET.ParseError as e:
        sys.exit(f"gen-readme-assets: {path.name} is not well-formed XML: {e}")

    # GitHub serves a README image as a bare <img>: no stylesheet, no script,
    # no fetch of a second file. Anything below would silently not apply.
    for bad, why in (
        ("<style", "a stylesheet does not apply inside an <img>"),
        ("class=", "class selectors have no stylesheet to match"),
        ("@import", "external resources are not fetched"),
        ("font-face", "webfonts are not loaded"),
        ("<script", "scripts do not execute"),
    ):
        if bad in svg:
            sys.exit(f"gen-readme-assets: {path.name} contains {bad!r} — {why}")

    ids = _ID.findall(svg)
    dupes = {i for i in ids if ids.count(i) > 1}
    if dupes:
        sys.exit(
            f"gen-readme-assets: {path.name} has duplicate ids {sorted(dupes)} — "
            "a later url(#id) would resolve to the earlier element"
        )


def render_all() -> dict[Path, str]:
    out: dict[Path, str] = {}
    for name, build in BUILDERS.items():
        for suffix, palette in (("", LIGHT), ("-dark", DARK)):
            path = OUT_DIR / f"{name}{suffix}.svg"
            svg = build(palette)
            validate(path, svg)
            out[path] = svg
    return out


def main(argv: list[str]) -> int:
    check = "--check" in argv
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []
    for path, svg in render_all().items():
        rel = path.relative_to(ROOT)
        if check:
            if not path.exists() or path.read_text() != svg:
                stale.append(str(rel))
            continue
        path.write_text(svg)
        print(f"wrote {rel}  ({len(svg.encode()):,} bytes)")
    if check:
        if stale:
            print(
                "docs/assets is stale — these no longer match a fresh render:\n  "
                + "\n  ".join(stale)
                + "\n\nRun: python3 scripts/gen-readme-assets.py",
                file=sys.stderr,
            )
            return 1
        print(f"docs/assets: {len(BUILDERS) * 2} images match a fresh render")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
