package agentdesigner

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/ilijad1/simple-agents/internal/coder"
)

// DesignState is the current step in the conversational agent creation wizard.
type DesignState int

const (
	StateIdle       DesignState = iota
	StateDescribing             // waiting for user description
	StateClarifying             // LLM asked clarifying questions, waiting for answers
	StateReviewing              // code generated, waiting for user approval
	StateDone                   // agent saved
)

func (s DesignState) String() string {
	switch s {
	case StateIdle:
		return "idle"
	case StateDescribing:
		return "describing"
	case StateClarifying:
		return "clarifying"
	case StateReviewing:
		return "reviewing"
	case StateDone:
		return "done"
	}
	return "unknown"
}

// DesignSession holds all state for one in-progress agent creation.
type DesignSession struct {
	UserID         string
	AgentID        string
	AgentName      string
	State          DesignState
	Description    string
	Clarifications string // questions generated by LLM
	Answers        string // user's answers
	GeneratedCode  string
	CreatedAt      time.Time
}

// Flow manages per-user design sessions and drives the FSM.
// It is safe for concurrent use.
type Flow struct {
	mu       sync.Mutex
	sessions map[string]*DesignSession // keyed by userID

	coder    *coder.Coder
	designer *AgentDesigner
}

// NewFlow creates a Flow.
func NewFlow(coderSvc *coder.Coder, designer *AgentDesigner) *Flow {
	return &Flow{
		sessions: make(map[string]*DesignSession),
		coder:    coderSvc,
		designer: designer,
	}
}

// Start creates a new design session for userID.
// Returns the opening prompt asking for a description.
func (f *Flow) Start(userID, agentName string) (string, error) {
	f.mu.Lock()
	defer f.mu.Unlock()

	if _, exists := f.sessions[userID]; exists {
		return "", fmt.Errorf("you already have an active design session; send /agent cancel to start over")
	}

	f.sessions[userID] = &DesignSession{
		UserID:    userID,
		AgentID:   uuid.New().String(),
		AgentName: agentName,
		State:     StateDescribing,
		CreatedAt: time.Now(),
	}

	return fmt.Sprintf(
		"Starting agent *%s*\\.\n\nDescribe what this agent should do\\. Be specific: what data should it fetch or monitor, what actions should it take, and what should it output?",
		escapeMarkdownV2(agentName),
	), nil
}

// Step processes one message from the user and advances the FSM.
// Returns (response, isDone, err).
func (f *Flow) Step(ctx context.Context, userID, input string) (string, bool, error) {
	f.mu.Lock()
	sess, ok := f.sessions[userID]
	if !ok {
		f.mu.Unlock()
		return "", false, fmt.Errorf("no active design session; use /agent create <name> to start one")
	}
	state := sess.State
	f.mu.Unlock()

	switch state {
	case StateDescribing:
		return f.stepDescribing(ctx, userID, input)
	case StateClarifying:
		return f.stepClarifying(ctx, userID, input)
	case StateReviewing:
		return f.stepReviewing(ctx, userID, input)
	default:
		return "", false, fmt.Errorf("unexpected state: %s", state)
	}
}

// Cancel removes the user's active session without saving anything.
func (f *Flow) Cancel(userID string) {
	f.mu.Lock()
	defer f.mu.Unlock()
	delete(f.sessions, userID)
}

// GetSession returns the user's active session, or nil.
func (f *Flow) GetSession(userID string) *DesignSession {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.sessions[userID]
}

// GenerateAndSave performs a single-shot code generation from name + description,
// runs guardrails, and saves the agent. No multi-turn session is created.
// This is used by the web UI create form where the user provides a full description upfront.
func (f *Flow) GenerateAndSave(ctx context.Context, userID, agentID, name, description string) error {
	prompt := fmt.Sprintf(`You are an expert Python developer. Generate a complete, production-ready automated agent script.

Agent name: %s
Description: %s

The script MUST follow this exact structure:
1. Module docstring (agent name + description)
2. Standard imports (os, json, sys, etc.)
3. The line: # ======= USER LOGIC =======
4. All custom logic, including a main() function
5. if __name__ == "__main__": main()
6. The line: # ======= SYSTEM INJECTED =======

Rules:
- NEVER use eval(), exec(), compile(), __import__(), os.system(), subprocess, or socket.socket()
- Access secrets via os.environ.get("SECRET_NAME", "")
- Send output to Telegram with print("[CHAT] your message")
- Handle errors gracefully; log failures with print("[ERROR] ...")
- Code must be self-contained and runnable with: python3 main.py

Return ONLY the Python code. No markdown fences. No explanation.`, name, description)

	result, err := f.coder.Generate(ctx, userID, prompt)
	if err != nil {
		return fmt.Errorf("generate code: %w", err)
	}

	code := cleanCodeFence(result.Text)

	if err := RunFullGuardrails(code, prompt); err != nil {
		return fmt.Errorf("guardrails: %w", err)
	}

	return f.designer.SaveAgent(userID, agentID, name, description, code)
}

// ─── FSM step handlers ────────────────────────────────────────────────────────

func (f *Flow) stepDescribing(ctx context.Context, userID, description string) (string, bool, error) {
	f.mu.Lock()
	sess := f.sessions[userID]
	sess.Description = description
	f.mu.Unlock()

	prompt := fmt.Sprintf(`You are an AI agent design assistant. A user wants to build an automated Python agent.

Agent name: "%s"
User's description: %s

Generate 3–5 concise clarifying questions to refine the requirements.
Focus on: external APIs or data sources, output format, authentication, error handling, scheduling.
Return a numbered list only — no preamble, no explanations.`, sess.AgentName, description)

	result, err := f.coder.Generate(ctx, userID, prompt)
	if err != nil {
		return "", false, fmt.Errorf("generate clarifying questions: %w", err)
	}

	f.mu.Lock()
	sess.Clarifications = result.Text
	sess.State = StateClarifying
	f.mu.Unlock()

	return fmt.Sprintf(
		"Got it\\! A few quick questions:\n\n%s\n\n_Answer all at once in your next message\\._",
		escapeMarkdownV2(result.Text),
	), false, nil
}

func (f *Flow) stepClarifying(ctx context.Context, userID, answers string) (string, bool, error) {
	f.mu.Lock()
	sess := f.sessions[userID]
	sess.Answers = answers
	name := sess.AgentName
	desc := sess.Description
	clarifs := sess.Clarifications
	f.mu.Unlock()

	prompt := fmt.Sprintf(`You are an expert Python developer. Generate a complete, production-ready automated agent script.

Agent name: %s
Description: %s
Clarifying questions that were asked:
%s
User's answers:
%s

The script MUST follow this exact structure:
1. Module docstring (agent name + description)
2. Standard imports (os, json, sys, etc.)
3. The line: # ======= USER LOGIC =======
4. All custom logic, including a main() function
5. if __name__ == "__main__": main()
6. The line: # ======= SYSTEM INJECTED =======

Rules:
- NEVER use eval(), exec(), compile(), __import__(), os.system(), subprocess, or socket.socket()
- Access secrets via os.environ.get("SECRET_NAME", "")
- Send output to Telegram with print("[CHAT] your message")
- Handle errors gracefully; log failures with print("[ERROR] ...")
- Code must be self-contained and runnable with: python3 main.py

Return ONLY the Python code. No markdown fences. No explanation.`,
		name, desc, clarifs, answers)

	result, err := f.coder.Generate(ctx, userID, prompt)
	if err != nil {
		return "", false, fmt.Errorf("generate code: %w", err)
	}

	code := cleanCodeFence(result.Text)

	if err := RunFullGuardrails(code, prompt); err != nil {
		// Guardrails failed — stay in StateClarifying so the user can adjust
		f.mu.Lock()
		f.sessions[userID].State = StateClarifying
		f.mu.Unlock()
		return fmt.Sprintf(
			"The generated code failed safety checks: %s\n\nPlease rephrase your requirements and try again\\.",
			escapeMarkdownV2(err.Error()),
		), false, nil
	}

	f.mu.Lock()
	sess.GeneratedCode = code
	sess.State = StateReviewing
	f.mu.Unlock()

	preview := codePreview(code, 40)
	return fmt.Sprintf(
		"Here's the generated code:\n\n```python\n%s\n```\n\nReply *yes* to save, *no* to regenerate, or *cancel* to abort\\.",
		preview,
	), false, nil
}

func (f *Flow) stepReviewing(ctx context.Context, userID, input string) (string, bool, error) {
	lower := strings.ToLower(strings.TrimSpace(input))

	switch {
	case lower == "yes" || lower == "y" || lower == "save" || lower == "approve" || lower == "ok":
		return f.saveAgent(userID)
	case lower == "no" || lower == "n" || lower == "regenerate" || lower == "retry":
		f.mu.Lock()
		sess := f.sessions[userID]
		answers := sess.Answers
		sess.State = StateClarifying
		f.mu.Unlock()
		return f.stepClarifying(ctx, userID, answers)
	case lower == "cancel" || lower == "abort":
		f.Cancel(userID)
		return "Agent creation cancelled\\.", false, nil
	default:
		return "Reply *yes* to save, *no* to regenerate, or *cancel* to abort\\.", false, nil
	}
}

func (f *Flow) saveAgent(userID string) (string, bool, error) {
	f.mu.Lock()
	sess := f.sessions[userID]
	f.mu.Unlock()

	if err := f.designer.SaveAgent(
		sess.UserID, sess.AgentID, sess.AgentName,
		sess.Description, sess.GeneratedCode,
	); err != nil {
		return "", false, fmt.Errorf("save agent: %w", err)
	}

	f.mu.Lock()
	delete(f.sessions, userID)
	f.mu.Unlock()

	return fmt.Sprintf(
		"Agent *%s* saved\\! Use /run %s to run it, or manage it from the web dashboard\\.",
		escapeMarkdownV2(sess.AgentName),
		escapeMarkdownV2(sess.AgentName),
	), true, nil
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

// cleanCodeFence strips leading/trailing markdown code fences from LLM output.
func cleanCodeFence(s string) string {
	s = strings.TrimSpace(s)
	for _, prefix := range []string{"```python", "```"} {
		if strings.HasPrefix(s, prefix) {
			s = strings.TrimPrefix(s, prefix)
			break
		}
	}
	if strings.HasSuffix(s, "```") {
		s = strings.TrimSuffix(s, "```")
	}
	return strings.TrimSpace(s)
}

// codePreview returns at most maxLines lines with a truncation marker.
func codePreview(code string, maxLines int) string {
	lines := strings.Split(code, "\n")
	if len(lines) <= maxLines {
		return code
	}
	return strings.Join(lines[:maxLines], "\n") + "\n# ... (truncated)"
}

// escapeMarkdownV2 escapes special characters for Telegram MarkdownV2.
func escapeMarkdownV2(s string) string {
	replacer := strings.NewReplacer(
		"_", "\\_", "*", "\\*", "[", "\\[", "]", "\\]",
		"(", "\\(", ")", "\\)", "~", "\\~", "`", "\\`",
		">", "\\>", "#", "\\#", "+", "\\+", "-", "\\-",
		"=", "\\=", "|", "\\|", "{", "\\{", "}", "\\}",
		".", "\\.", "!", "\\!",
	)
	return replacer.Replace(s)
}
